### ISSUE TITLE
Receiving "No linter providers" notification despite having linter providers

### ISSUE THREAD

**Issue by sirianni** [atom-community/linter#1000]
After the latest update, I'm receiving the "No linter providers" notification message despite having linter providers installed.  Everything else is working perfectly fine, as before.

**Comment by steelbrain** [comment]
Thanks for the report, I'll investigate!

**Comment by steelbrain** [comment]
@sirianni Have you tried restarting the editor by the way?

**Comment by sirianni** [comment]
Yes, multiple times.

**Comment by steelbrain** [comment]
Can you please tell us which linter providers you have installed?

**Comment by sirianni** [comment]
```
$ apm list | grep linter
├── linter@1.11.0
├── linter-jscs@3.2.0
├── linter-jshint@1.2.1
```

**Comment by steelbrain** [comment]
Fixed by #1001

**Comment by ppvk** [comment]
Thank you!

**Comment by steelbrain** [comment]
A patch release is available with the fix
