### ISSUE TITLE
not linting it shows its all ok

### ISSUE THREAD

**Issue by renoirfaria** [atom-community/linter#1003]

**Comment by steelbrain** [comment]
Have you installed the providers yet? http://atomlinter.github.io/

**Comment by renoirfaria** [comment]
yep it's installed and always showing No Issues

**Comment by steelbrain** [comment]
Can you please provide us a repro case? Also can try installing linter-jshint file and then open a javascript file?

Please note that linters are grammar specific

**Comment by renoirfaria** [comment]
After installing linter-jshint it works!! Thank you so much!
