### ISSUE TITLE
Linter not catching up until saving

### ISSUE THREAD

**Issue by OmgImAlexis** [atom-community/linter#1004]
I've found in files with 1k+ lines the linter can get to the point where it's too slow to lint inline and as I type I get errors that just "stick".
For example this error didn't go away at all until I saved even though it picked up other errors that I fixed in a few lines below it.

![screen shot 2015-11-15 at 2 42 33 pm](https://cloud.githubusercontent.com/assets/6525926/11167180/33415b84-8ba7-11e5-9ae0-59e98237849d.png)

Edit: This file has over 1900 lines and I don't get the same issue with smaller files.

**Comment by OmgImAlexis** [comment]
Not sure if this is related as well but the first lint issue shown in the bottom dialog is the `generator_name` issue on line#1332 even though on the sidebar line#1325 has an issue.

![screen shot 2015-11-15 at 3 13 30 pm](https://cloud.githubusercontent.com/assets/6525926/11167273/7a978108-8bab-11e5-8880-186ca1d03723.png)

**Comment by steelbrain** [comment]
Can you please upload a file like that somewhere so we can use it to benchmark linter? Also we have a performance tuning section in the README. If you want performance with that much number of errors, you should disable inline bubbles.

**Comment by steelbrain** [comment]
About the not catching till save, maybe you have disabled `lintOnFly`, so it's only linting the file on save

**Comment by OmgImAlexis** [comment]
@steelbrain https://github.com/OmgImAlexis/SickRage/blob/movejs-to-object/gui/slick/js/core.js

Shouldn't the linter work even if the file is large, I get that it could take a few seconds but what I was saying is at times it'll "miss" some changes I've made. I could fix an error on let's say line 200 and it'll still think the error's there even though I can change line 201 and it'll update immediately and after that line 200 will still have the error showing even though it's fixed. 

I'll look into the inline bubbles option, I almost have the file fixed now. I just figured if this was a bug instead of a performance issue then it should be reported as it may be an edge case that hasn't been seen before.

**Comment by steelbrain** [comment]
@OmgImAlexis I have a fix planned that will make the performance of inline bubbles `O(0)` instead of `O(log n)`

**Comment by Arcanemagus** [comment]
This is similar behavior to what I've been talking about over in #1002. I wonder if `linter` somehow gets "stuck" when a provider hasn't returned by the time `linter` requests a lint again?

**Comment by OmgImAlexis** [comment]
Also you'll notice on here it's getting line number mixed up. Again this only happens with large files.

![screen shot 2015-11-15 at 5 39 44 pm](https://cloud.githubusercontent.com/assets/6525926/11167853/875d7eec-8bc4-11e5-9375-57fbafd955b0.png)

**Comment by OmgImAlexis** [comment]
@Arcanemagus we had the same issue with the python-pep8 linter in atom and the linter-jshint.

**Comment by Arcanemagus** [comment]
If you are talking about https://atom.io/packages/linter-python-pep8, then you should look into an alternative Python `linter` plugin, that one hasn't been updated to the new API and will never actually run. You probably want to be using one of the linters listed here: http://atomlinter.github.io/

**Comment by OmgImAlexis** [comment]
@Arcanemagus I couldn't remember it off hand, we've tried all of the ones on there and most of them give us the same issue as https://github.com/atom-community/linter/issues/1002

**Comment by steelbrain** [comment]
This has been fixed in https://github.com/atom-community/linter/commit/bbd7ea8e24c25bfc3f33375c3fbae03e136c5fa2

Linter now allows as many lint runs as possible, and doesn't do locking of any kind but only uses the results from the latest invocation

**Comment by steelbrain** [comment]
@OmgImAlexis that commit is in a PR and hasn't been merged yet, I would like to keep this open until it's merged
