### ISSUE TITLE
Specification of the new UI

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#1006]
Here's what I have in mind so far

 - No more buttons
 - Have a checkbox that allows users to show errors from all files when enabled
 - Move the inline bubbles to gutter (HUGE performance improvement)

If you have any suggestions/comments, please do post them below
cc @simurai

**Comment by AsaAyers** [comment]
> Move the inline bubbles to gutter (HUGE performance improvement)

Can you mockup what this would look like? I don't care about performance improvements near as much as I care about usability because the linter is fast enough for everything I write.

**Comment by steelbrain** [comment]
@AsaAyers As an example, you can goto http://hacklang.org/ and wait for the in-browser IDE to load. When it's done, just mouse over the gutter tooltips and you'll get an idea of what it'll look like in linter.

**Comment by AsaAyers** [comment]
Please consider those of us that rarely touch the mouse. I need to see the error near my cursor without touching the mouse.

There is a selection at the bottom to show the error on that line, but it's often way too far away.

![selection_202](https://cloud.githubusercontent.com/assets/324999/11243950/1302ffc4-8dd9-11e5-904e-c23b9f777465.png)

**Comment by steelbrain** [comment]
@AsaAyers You'll be able to choose the behavior, we are considering splitting UI into a separate package, that way you'll have two packages, one that gives you the current UI and one that favors performance

**Comment by DanPurdy** [comment]
I think it would be really nice to able to get a slide out panel with all the linting issues from every linter/file displayed in a list. Such as with the TODO plugin.
![screen shot 2015-11-19 at 16 05 03](https://cloud.githubusercontent.com/assets/1386054/11275829/618f2c68-8ed7-11e5-9bf4-dd45d142797c.png)

**Comment by simurai** [comment]
How about something like:

![linter-panel](https://cloud.githubusercontent.com/assets/378023/11361363/65af8d18-92d0-11e5-8112-3d43a4f8d9ff.png)

- Only show the `N issues` in the status-bar
- You can toggle the Error Panel with a keybinding or click the `N issues` in the status-bar
- The Error Panel shows a list of all errors/warnings
- Top right of the Error Panel there is a toggle to switch between linting in "Current file" or "All files"

**Comment by steelbrain** [comment]
@simurai that looks beautiful, did you see the images I sent you of the current state of panel?

Also, we might have to rename the `Lint in` to `Show messages from`. Because we don't lint all files, we just show messages from all text editors when `All files` is selected

**Comment by simurai** [comment]
> did you see the images I sent you of the current state of panel?

Yes, like this:

![screen shot 2015-11-27 at 11 20 08 am](https://cloud.githubusercontent.com/assets/378023/11432817/e7b45f9e-94f8-11e5-86d2-ce1869a7c938.png)

My thinking was that having a permanent linter bar might be too much. Like in the above screenshot, the only information that I would care is the `No Issues`. So having a whole bar for that seems like wasting space and it could be shown in the status-bar instead. There will be the "all files" checkbox, but I think it's not that important to have it permanently visible. If you wanna change it, you would open the panel first. Feel free to disagree.. :wink:

**Comment by simurai** [comment]
:+1: Changed the to `Show messages from`.

![linter-panel](https://cloud.githubusercontent.com/assets/378023/11432954/c5036a42-94fa-11e5-99e5-7e96b67d19d5.png)

**Comment by simurai** [comment]
__Question__: Would it be possible to show the nr of issue (3 Issues) in the status-bar for all files, even if I switch to only show messages from the current file (Errors: 1) in the panel?

![screen shot 2015-11-27 at 11 43 25 am](https://cloud.githubusercontent.com/assets/378023/11433116/42f3777a-94fc-11e5-921f-d738e28253c6.png)

Or is that confusing? It would have the benefit that I can keep only showing `Current file`, but still know that there are errors in other files.

**Comment by steelbrain** [comment]
@simurai There is already a config for that `Scope of Bottom Status` or something

**Comment by simurai** [comment]
Found it. Ok, great.

**Comment by kepler0** [comment]
@simurai I like the toggle but some users could have issue with it. Some users wanted to have the bottom panel show the lint issues on the current line. See #587.

**Comment by steelbrain** [comment]
@kepler0 I am personally :-1: from all the experience with current line tab of bottom panel. We are going to solve it a bit differently this time. This time instead of having the panel show errors for a line, users can just hover the gutter and see all messages for that line

**Comment by kepler0** [comment]
As long as issues on one line are considered, especially in the previously
known use cases, we should be good.

**Comment by dsandstrom** [comment]
> This time instead of having the panel show errors for a line, users can just hover the gutter and see all messages for that line

@steelbrain : @AsaAyers brought up a good point that you may be forgetting about users who rather not use the mouse.

Most of the time, I prefer to see only the single line's linter error instead of the entire project/file/N lines.  However, when I'm going to fix the linting errors for the entire file, I toggle the "File" button.  I rarely use the "Project" button and, in fact, hide it with the settings.  In addition, I prefer the error at the bottom of the file instead of in a tooltip because I feel that the tooltip gets in the way of writing code.  Also, the tooltiip conflicts with overlays like autocomplete.  I say that the tooltip gets in the way because many linters add an error when you have a space at the end of the line, so every time you press space, you will have a bubble pop up that blocks the code underneath the current line.

>  You'll be able to choose the behavior, we are considering splitting UI into a separate package, that way you'll have two packages, one that gives you the current UI and one that favors performance

This does not seem like a good long term solution.  I feel like the "current UI" branch will not be maintained and will break eventually.

**Comment by simurai** [comment]
I see the point about "only show a panel message when my cursor is over an error".

Well, we *could* just keep it as is, but move the "tabs/buttons" into the panel:

![linter-panel-line](https://cloud.githubusercontent.com/assets/378023/11455109/a9056b56-968f-11e5-8c08-27e386d93761.png)

**Comment by AsaAyers** [comment]
* No more buttons
  * Why? Just because you don't like buttons?
* Have a checkbox that allows users to show errors from all files when enabled
  * This is what the Project tab is for
* Move the inline bubbles to gutter (HUGE performance improvement)
  * Performance improvements are nice, but do we have a real problem here, and does this require redesigning the whole UI?

**Comment by steelbrain** [comment]
@AsaAyers Just a side note that the tabs are __very__ confusing for a lot of people

**Comment by steelbrain** [comment]
@simurai Your last panel design looks good, We should have a minimize button on it though like we have in the experimental branch ![Maximized](http://i.imgur.com/IfSAa7Y.png) ![Minimized](http://i.imgur.com/COWs7d4.png)

**Comment by AsaAyers** [comment]
> Well, we could just keep it as is

This is what prompted me to try to find out, why does any of this need to change? The whole project is less than a year old, how is it we need to redesign the whole UI? Why can't you just make incremental changes to fix the actual problems vs scrap the whole UI and build a new one?

**Comment by steelbrain** [comment]
After evaluation of the options available, here's what I have decided

 - We will keep all three tabs
 - We will move all tabs to the panel

Just like shown in @simurai's image. We will be keeping inline bubbles as the default behavior and will be implementing gutter tooltips in the future (not now).

@AsaAyers We are factoring out linter ui into a separate package, that way community can write their own linter UIs, while we were at it, we decided to solve some long-due issues.

Does anyone have any further suggestions?

**Comment by kepler0** [comment]
:+1:

**Comment by varemenos** [comment]
Did you guys consider block decorations for the errors as an alternative to tooltips (and maybe even the panel itself)?

**Comment by Arcanemagus** [comment]
@varemenos Just filed https://github.com/AtomLinter/linter-ui-default/issues/39 so it can be tracked there.

**Comment by steelbrain** [comment]
Closing as the work/discussions of the new UI should be brought up in it's repo
