### ISSUE TITLE
Very unpredictable and buggy behaviour when file is open in multiple panes

### ISSUE THREAD

**Issue by KnutHelland** [atom-community/linter#1007]
Hi,

Sorry for an unspecific title and not much information. I want to give a brief description now, and _if this isn't an already known issue, I'll investigate, update title and post more information on this issue_.

I've used the linter for months now, and there is a bug annoying me all the time. If I have the same file open in multiple panes (which I do a lot. Split screen into the same file), it behaves very buggy and unpredictable. Often new errors are displayed only in one of the panes, but if I fix the error, I have to go back to the other pane and save the file from there before it gets linted again so the error disappears.

This happens with both `linter-eslint` and `linter-less`, so it is probably a problem with `linter` itself.

**Comment by steelbrain** [comment]
That is a known one, I have a fix in mind

**Comment by steelbrain** [comment]
Blocked on #1006 for now
