### ISSUE TITLE
Move the inline bubbles to gutter

### ISSUE THREAD

**Issue by simurai** [atom-community/linter#1011]
This issue is the 3rd point of [Specification of the new UI](https://github.com/atom-community/linter/issues/1006). But I think it would be good to have a separate discussion so it doesn't get mixed with the status-bar/panel changes.

- Move the inline bubbles to gutter (HUGE performance improvement)

![linter-tooltip](https://cloud.githubusercontent.com/assets/378023/11432672/a4055aca-94f6-11e5-9822-840cc2374bd7.png)

**Comment by simurai** [comment]
@steelbrain Is the only reason the "HUGE performance improvement"? Do you have some more details about it?

Something that needs to be tested. Currently the `.gutter` has `overflow: hidden`, probably added to improve performance, since nothing leaks out. But if the linter tooltips will move to the gutter, then they need to overlap and that might add some performance penalty and then the difference might not be that big. This is just a wild guess, so it needs to be verified if really true.

In case the performance difference is not too big, I kinda prefer the current version where the tooltip is inline, just next to the error. Otherwise you read the error message and then you have to try to find where the actual error is.

**Comment by steelbrain** [comment]
@simurai Here's the explanation for the performance improvement. Currently, everytime the user changes the cursor (user does this all the time), we get the performance hit of `O(n)`. We have to iterate all of the messages and check each message if it belongs to the current range. It slows the editor down significantly. Now if we move that bubble from inline to gutter, we are letting chrome do everything for us and tell us when it's hovered, we do no checking of any kind on cursor change so the cursor change now has `O(1)` performance penalty which is *very* appealing to me.

It also solves the issue we had about displaying multiple messages in shared range.

Now while I was working on this, some thoughts have crossed my mind, which can reduce the performance penality of the bubble to be a *lot* less, think of it as upto 99% improvement on large error counts, but `O(1)` is still appealing to me :stuck_out_tongue: I am not sure what to do to be honest.


We could give both to the user as a choice, what is your opinion?

**Comment by simurai** [comment]
Ok, yeah, avoiding the "iterate all of the messages on cursor change" sounds appealing to me too. :smile:

> We could give both to the user as a choice

Yes, maybe good idea. The new default would be in the gutter, but people could move it back inline, if they really wanted.

If we do that, might be nice if all the markup and CSS classes could be shared. Maybe rename `<div id="linter-inline">` to a more generic `<div id="linter-tooltip">`. So only the position would change, but the rest would stay the same.

**Comment by steelbrain** [comment]
I think I'll just avoid the tooltip logic for now and try to improve the inlining one, I'll add tooltips if they are worth it after the tuning to inline bubbles.

**Comment by IanVS** [comment]
With this change (moving to the gutter), will all tooltips always be displayed?  Or, would there be a way to hide them?  In fact, I would say they should probably be hidden by default, unless clicked on (similar to how Brackets Interactive Linter works).  The reason for this is that with the tooltip showing, it would be impossible to see what is on the line below the error.  Currently, you can at least move the cursor and get the message to go away. 

Or maybe I am misunderstanding the proposal here.

**Comment by steelbrain** [comment]
@IanVS if we move the tooltips to gutter, they'll only be shown on hover

**Comment by IanVS** [comment]
:+1:, then!

**Comment by Arcanemagus** [comment]
Just to put what we talked about a few days ago down somewhere, what I propose for this update is to release an update to `linter` before the new UI is released that includes the configuration change at a default value of inline (current behavior). Then when we release the new UI the default is changed to the gutter.

This way current users don't suddenly get things "broken", and new users are defaulted to the better performance option.

**Comment by steelbrain** [comment]
After some wild experiments, I was able to optimize inline bubbles enough to match their performance nearly with the gutter ones. I guess it's safe to say that gutter tooltips are a thing of future. We don't need them at the moment
