### ISSUE TITLE
Package activation time

### ISSUE THREAD

**Issue by csholmq** [atom-community/linter#1028]
![image](https://cloud.githubusercontent.com/assets/1297882/11842334/53525de6-a403-11e5-921b-132ada7234df.png)

Takes ~350 ms to activate the package. How come?

**Comment by steelbrain** [comment]
Dupe of #1026

**Comment by csholmq** [comment]
Sorry about that!

**Comment by steelbrain** [comment]
It's okay, happens to all of us :)
