### ISSUE TITLE
Lint when file is opened, but not while typing

### ISSUE THREAD

**Issue by mjomble** [atom-community/linter#1034]
It seems that if "Lint as you type" is disabled, linting is only performed on save.

It would make sense to me if the file was also linted once when you open it.

Otherwise, if I want to check if a file has any errors, I need to either make a dummy change and save the file or enable "Lint as you type".

If there are arguments for not doing this by default, then perhaps an additional "Lint on open" setting could be added.

**Comment by Arcanemagus** [comment]
You can also just save a file immediately after opening, the trigger is still ran even though the file hasn't been modified.

Linting on open when "Lint as you type" isn't enabled sounds like a good idea to me in any case.

**Comment by steelbrain** [comment]
Lint on file open is too expensive, imagine you opened a jquery dist file and jshint/eslint polluted your editor. If you want to lint a file on open, just press `ctrl + s` without doing anything, it would trigger a lint
