### ISSUE TITLE
Duplicate entry for same line & column behavior?

### ISSUE THREAD

**Issue by satazor** [atom-community/linter#1037]
I was hacking `linter-stylelint` provider which may return 2 different entries for the same line & column but with a different error and type. I've noticed that this causes a visible "bug" in the editor as seen bellow:

<img src="https://i.imgur.com/pdNFWPg.png">

`stylelint` is returning two entries for the 6th line in which the warning appears first and then the error. Note the color inconsistency between the gutter & highlight color and the tooltip. The gutter & highlight is showing me the error while the tooltip is showing me the warning.

The question here is if it is the `linter` responsibility to handle this in a consistent manner or should this be delegated to the provider?

Thanks

**Comment by steelbrain** [comment]
What do you propose for this? Should we show all messages that match the current range in the bubble?

**Comment by Arcanemagus** [comment]
I thought this was planned to be fixed with the UI re-write?

**Comment by steelbrain** [comment]
@Arcanemagus Its a very small change (<~ 20loc) in the rewrite branch. We can add it anytime we want

**Comment by satazor** [comment]
I think that this should be handled by the core `linter` and not be delegated to the provider, otherwise we might have fragmented and inconsistent solutions to the same problem.

In terms of UI, we should give priority to the first entry of type `error`. If possible I would display all entries in the tooltip, one for each entry ordered by type error while keeping the original order for the same type.

**Comment by steelbrain** [comment]
@satazor That's what the idea is, to handle it in the base linter. I'm thinking about showing all errors that match the given range

**Comment by satazor** [comment]
@steelbrain by bubble you mean the tooltip? If so, yes I would show all messages there, errors first then warnings, but keeping the original order of messages for the same type.

**Comment by steelbrain** [comment]
Closing in favor of https://github.com/AtomLinter/linter-ui-default/issues/12

**Comment by steelbrain** [comment]
Fixed in the new UI in https://github.com/AtomLinter/linter-ui-default/pull/13
