### ISSUE TITLE
Error: Can't parse config file .jshintrc

### ISSUE THREAD

**Issue by amucinom** [atom-community/linter#1040]
Hello!

I seem to be getting a weird error when adding .jshintrc files into my projects. I had created a backbone.js project using Yeoman go doing

```
yo backbone
```
and it creates the project for you. It includes a ```.jshintrc``` file with predetermined configurations. However, when I open any other ```.js``` file, I get this error
<img width="470" alt="screen shot 2016-01-06 at 4 17 18 pm" src="https://cloud.githubusercontent.com/assets/4065569/12158067/e2a28214-b493-11e5-86a3-5d5093dfc55f.png">
I tried to test it with a new empty folder, created two files, another ```.jshintrc```  with a couple of configs and another ```.js``` file with a couple of lines of code, and got the same error

I was wondering if you guys have heard of this issue before or if there's an easy fix for it!

Cheers!

**Comment by Arcanemagus** [comment]
Which linter plugins do you have enabled? It looks like at least you have `linter-javac`, and I'm assuming `linter-jshint`?

From what it looks like this is most likely an error from the actual linter program being called that is being passed on to you. Does `jshint` give you the same error when run in the command line?

**Comment by Arcanemagus** [comment]
Actually, closing in favor of https://github.com/AtomLinter/linter-jshint/issues/189.
