### ISSUE TITLE
What are `grammarScopes`?

### ISSUE THREAD

**Issue by josiahsprague** [atom-community/linter#1043]
I can't find any documentation about `grammarScopes`. The only thing I can find is a brief note here https://github.com/atom-community/linter/wiki/Linter-API which doesn't explain what `grammarScopes` are. Can someone point me to the correct documentation for that?

**Comment by kepler0** [comment]
It's equivalent to an Atom grammar. Look to Atom's documentation for more
information.

**Comment by Arcanemagus** [comment]
If you are looking for a reference, this is a great resource: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

This also is a great place to see what languages you can use when using \`\`\` with a block of code comment here on GH :wink:.
