### ISSUE TITLE
Bug when counting the number of issues in project

### ISSUE THREAD

**Issue by looterz** [atom-community/linter#1044]
At the bottom of the workspace under the warning/issue box, there are tabs that will show you the number of issues in the current file, and the project as a whole. It does not distinguish whether or not the file containing issues is actually within the project, and counts issues from any file open in an atom tab.

For instance, you can have an atom project containing one file open, and a file that is not within this project in an atom tab, and it will count any issues from the out-of-project file as issues from within the project. An easy fix would be to check that the file is actually within the project's workspace before counting it as an issue within the project.

**Comment by steelbrain** [comment]
The project tab basically means `Issues from all known or opened files`. It has been fixed in the UI rewrite
