### ISSUE TITLE
"Show Inline Error Tooltips" toggle off behavior

### ISSUE THREAD

**Issue by kbrose** [atom-community/linter#1047]
A really minor bug: toggling the "Show Inline Error Tooltips" option off while an inline error tooltip is currently being displayed causes the tooltip to remain there permanently (or, at least until the option is toggled back on and the cursor is moved).

Repro steps:

1. Have "Show Inline Error Tooltips" option turned **on**.
2. Have two panes open, one open to a file of code and the other with settings open.
3. Create code that will be caught by a linter.
4. Put the cursor at the beginning of the offending line, causing a tooltip to appear.
5. Switch panes and go to the settings for the Linter package.
6. Toggle the "Show Inline Error Tooltips" option to **off**.
7. Go back to panel with code, tooltip remains open, moving cursor around does not remove it.
8. Go back to settings, toggle the "Show Inline Error Tooltips" option back to **on**.
9. In the code panel, click to a line to remove the tooltip.
10. One last time, go to the settings and toggle the "Show Inline Error Tooltips" option to **off**.
11. Code is now free of tooltips, as expected.

See the attached picture. Notice (a) the tooltip is displayed, (b) the "Show Inline Error Tooltips" is unchecked, and (c) the cursor location is several lines below the line with the tooltip.

![inline-error-tooltips-bug](https://cloud.githubusercontent.com/assets/4053170/12375596/297641be-bc8f-11e5-8a5a-126037b88c40.png)

Windows 10
Atom 1.4
Linter 1.11.3

**Comment by steelbrain** [comment]
I think this has been fixed in the UI rewrite

**Comment by steelbrain** [comment]
Confirmed, this has been fixed in the new UI
