### ISSUE TITLE
Improving "as you type" linting

### ISSUE THREAD

**Issue by thejameskyle** [atom-community/linter#1050]
I turn the typing lint interval up to 2000 so it isn't interruptive to typing. However, the delay after correcting an error is bothersome. So it'd be nice to have an additional option that will lint at a higher interval when there's an error.

**Comment by Arcanemagus** [comment]
If a user has set a delay high enough that that becomes an issue, what happens if we have a 'speedup when there is an error"? It will be faster until the error is fixed, potentially staying at the fast speed for a while... which is against what the user asked for in the first place.

**Comment by thejameskyle** [comment]
That's true, is there any information about the position (line, column) of the error that could be used to identify cases where the user is editing the code around the error?

**Comment by Arcanemagus** [comment]
The error you are fixing may have nothing to do with the current position of the cursor (missing `)` for example).

**Comment by thejameskyle** [comment]
ok
