### ISSUE TITLE
[wishlist] Minimum width for decorations

### ISSUE THREAD

**Issue by sorear** [atom-community/linter#1055]
I'm using `linter-js-standard` and it's somewhat annoying that zero-width error spans don't give a visual indication of the column with the error.  I think it would be more useful if error spans were forced to at least one character so that the highlight would always show up.  Thoughts?

Good: ![image](https://cloud.githubusercontent.com/assets/92735/12538530/78d81898-c290-11e5-80f4-4c8d445d795b.png)

Bad: ![image](https://cloud.githubusercontent.com/assets/92735/12538522/5f66c788-c290-11e5-9055-9b2f006b4c1f.png)

**Comment by Arcanemagus** [comment]
Sounds like a decent idea to have here in the core, you should also point the author of `linter-js-standard` at the [atom-linter](https://github.com/AtomLinter/atom-linter) helper library, one of the functions is `rangeFromLineNumber` which creates a range from the specified column to the end of the line automatically.

**Comment by Dirbaio** [comment]
+1. linter-pylint also does zero-width errors and it's very annoying. 

It would be nice if linter core would display these properly. :)

**Comment by Arcanemagus** [comment]
A lot of these issues are due to `helpers.parse()` returning 0 length ranges.... I think it's high time I go and fix that :stuck_out_tongue:.

**Comment by steelbrain** [comment]
I don't think we want this. If something has a 0-width range then it means the provider is messing it up. and we need to trigger errors to help us investigate. Thanks for asking though @sorear
