### ISSUE TITLE
Provide setting for custom path to a [per linter] global [fallback] config in the API?

### ISSUE THREAD

**Issue by danielbayley** [atom-community/linter#1056]
While I agree that when working on large/r projects, config files should be kept with the project; I think it’s good to have a global config for each linter as a fallback if one doesn’t exist. Also what if I have a bunch of smaller/private projects which I want to share a common config?

As it stands, some `linter-` packages have this option and others don’t. This inconsistency leads to this seemingly unnecessary “meta" configuration headache. Often the suggestion is to further pollute the `HOME` directory with yet _another_ `.` file, which I don’t want to do.

Is this something that could be addressed with this package’s API, or do all `linter-` packages implement their own settings independently?

[`linter-sass-lint`](https://github.com/AtomLinter/linter-sass-lint) is a good example of having these options.

**Comment by Arcanemagus** [comment]
The `linter-*` packages contain the settings that control how the linter they act as a provider for is ran, this package has as little as possible to do with that on purpose. Several linters don't even offer the ability to override their config detection meaning this is impossible for quite a few `linter-*` plugins in the first place.

If something like this were to be moved to the (already quite large) settings of this package, how would you generalize settings across _all_ linters? How would you handle 3rd party providers that don't respect the configuration settings? What about providers that simply haven't been updated yet?

Moving those settings into here would be a nightmare :stuck_out_tongue:.
