### ISSUE TITLE
How do linters get added to the list?

### ISSUE THREAD

**Issue by biffen** [atom-community/linter#1067]
I've made a linter ([linter-cppcheck](https://atom.io/packages/linter-cppcheck)), and I'd like it to be added to the [*Full linters list*](http://atomlinter.github.io/) (under C and C++), but I can't seem to find any documentation on how to add it.

**Comment by steelbrain** [comment]
We have a [atomlinter.github.io repo](https://github.com/atomlinter/atomlinter.github.io). You can [PR](https://github.com/AtomLinter/atomlinter.github.io/pulls?q=is%3Apr+is%3Aclosed) your linters there
