### ISSUE TITLE
Lint As You Type not working

### ISSUE THREAD

**Issue by GLodi** [atom-community/linter#1079]
I've recently installed linter and linter-clang. They work fine, but I'm tired of constantly saving the file to check for errors. I noticed the Lint As You Type feature (which was activated by default), but it doesn't seem to work: errors are shown only when the file is saved, not as I type.
Is this a common problem? I should add that I'm under OSX 10.11.2 and Atom 1.5.1.

**Comment by florianb** [comment]
Hi @GLodi - this issue belongs to the https://github.com/AtomLinter/linter-clang package. `linter-clang` has currently no support for linting on the fly implemented.

**Comment by steelbrain** [comment]
Closing based on comment above, Thanks @florianb
