### ISSUE TITLE
PHP Linter Error

### ISSUE THREAD

**Issue by TJProgrammer** [atom-community/linter#1081]
Hello!
When the linter checks a PHP file, it gives this error:
```
Error: Invalid TextEditor provided
    at _validateEditor (/home/informatica/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:143:11)
    at Object.rangeFromLineNumber (/home/informatica/.atom/packages/linter-php/node_modules/atom-linter/lib/helpers.js:164:3)
    at /home/informatica/.atom/packages/linter-php/lib/main.coffee:58:30
```
What can cause this error?
Thanks.

**Comment by Arcanemagus** [comment]
There are two causes, one easy to fix, the other rather difficult:

* Your Atom is out of date (<1.4.0), update Atom and this will be fixed :stuck_out_tongue:
* The `atom-linter` helper module is out of date, unfortunately making sure all your installed versions of it are up to date, and that Atom is loading the right one can be a huge pain.

**Comment by TJProgrammer** [comment]
Thank you!
