### ISSUE TITLE
Documentation links for messages

### ISSUE THREAD

**Issue by sergeychernyshev** [atom-community/linter#1082]
I'd like for my team to be able to click on information icon next to each message and open up a page in web browser that gives extensive detailed explanation of the issue (specific linters will have to provide such URLs).

For example, I'm already working on [adding documentation URLs for CSSLint](https://github.com/sergeychernyshev/csslint/commit/4c3bb288e8a6ce3df38bbec24e8d95200d8cb503) and hope to surface them in [linter-csslint](https://github.com/AtomLinter/linter-csslint) eventually.

I'll also be interested in adding this kind of documentation URLs to ESLint rules as well, when this is available.

How can we go about making it happen?

**Comment by Arcanemagus** [comment]
That should be placed as an element in the `trace` message property, and I _believe_ that you can specify the `html` property of the trace message instead of the `text`, and get a clickable link.

**Comment by sergeychernyshev** [comment]
@Arcanemagus is there a linter that uses html property already that I can look at for reference?

**Comment by Arcanemagus** [comment]
`linter-eslint` has the capacity to use it for regular messages, see [here](https://github.com/AtomLinter/linter-eslint/blob/v6.0.0/src/main.js#L154-L159). Trace messages are essentially the exact same thing as regular messages, but only show in tooltips.

**Comment by sergeychernyshev** [comment]
Thank you. I looked at the code, it seems to be straightforward to add links to linters themselves.

Let me try adding links to it to see how it all works with `<a>` tags and opens the browser. And if all good there, we can close this issue.

**Comment by steelbrain** [comment]
This has been implemented in linter-eslint
