### ISSUE TITLE
Copiable text in issues pane

### ISSUE THREAD

**Issue by alist** [atom-community/linter#1083]
I'd like to be able to copy issue text so I can Google it. 

![Highlighted issue text](https://cloud.githubusercontent.com/assets/499382/13116515/3e8edffe-d56a-11e5-9cc0-a105199eea25.png)

In Atom on OSX, I can't `command-c` or get a right-click menu!

**Comment by steelbrain** [comment]
CTRL + C should work

**Comment by alist** [comment]
It works. What does it take to switch it to `CMD - C`?

**Comment by steelbrain** [comment]
Not much, but this UI and everything has already been replaced and has changes waiting to be merged, can you re-open this in https://github.com/AtomLinter/linter-ui-default?
