### ISSUE TITLE
Linter package seems to hang atom

### ISSUE THREAD

**Issue by dragonxlwang** [atom-community/linter#1084]
I am experiencing atom hanging whenever linter package is used --- for python files, linter-flake8 or for c files linter-clang. I have report the problem to linter-flake8 package initially (https://github.com/AtomLinter/linter-flake8/issues/159) until that I found all linter related packages makes the atom hangs.

I have tested both flake and clang which works fine standalone. I also tested when there is only linter-clang/linter-flake8 with linter package in atom when it always hangs in both cases. I am not sure what possibly in linter package that cause atom freeze.

Mac OS X El Captain
Atom: 1.5.3
Packages
$ atom_ls_installed_packages
linter@1.11.3
linter-flake8@1.11.0

**Comment by steelbrain** [comment]
This linter package does not do any linting or any operations that possibly could cause Atom to hang, please open and discuss this in specific linters you're experiencing problems in

**Comment by dragonxlwang** [comment]
thanks!
