### ISSUE TITLE
Only one line linted at a time

### ISSUE THREAD

**Issue by tofl** [atom-community/linter#1085]
I have installed this linter and `linter-php` and I noticed that when I have multiple errors in my file/project, it notices me of only 1 error at a time.
For instance, if I have an error on line 10 and an error on line 80, it will only tell me about the error on line 10. It will warn me about the second error (line 80) only when I will have solved the one on line 10.

I have created [this topic](https://discuss.atom.io/t/php-linter-doesnt-lint-all-the-file/25894) on discuss.atom.io, but didn't get any answer to the problem.

**Comment by steelbrain** [comment]
cc @Arcanemagus

**Comment by Arcanemagus** [comment]
This is a limitation of `php`, it's a syntax checker _only_, not semantic. And being a rather simple one it simply exits on the first error it finds.

For a semantic checker you should look into `phpmd`, for a stylistic checker look into `phpcs`.

I personally use a combination of all 3 together.

**Comment by tofl** [comment]
Ok thanks I'm gonna do that.
