### ISSUE TITLE
Option to hide warnings from error panel

### ISSUE THREAD

**Issue by ProLoser** [atom-community/linter#1088]
I like warnings inline and don't mind configuring them on a linter-by-linter basis.

However, I treat warnings on a case-by-case  basis, and don't feel it's necessary to consider them when thinking about the 'big picture' of looking at an entire file (or project).

it would be nice if I could show warnings and errors inline, but filter the error panel (which is a file/project summary) to only errors. This way I am treated with a global notification of issues I NEED to fix vs issues I MIGHT want to fix.

**Comment by steelbrain** [comment]
1. This type of configuration should be provided by linter providers themselves
2. We have a config of ignored message types but it has been removed in master and will not be a part of the next release

**Comment by ProLoser** [comment]
I do not want to ignore warnings. Please reopen this. I want to hide them from the ERROR PANEL. I do NOT want to hide them from inline feedback.

**Comment by steelbrain** [comment]
Oh, interesting

**Comment by Arcanemagus** [comment]
Should this be moved over to [linter-ui-default](https://github.com/AtomLinter/linter-ui-default)?

**Comment by steelbrain** [comment]
Moved [`here`](https://github.com/AtomLinter/linter-ui-default/issues/43)
