### ISSUE TITLE
Underline before actual error position

### ISSUE THREAD

**Issue by gabmontes** [atom-community/linter#1091]
The underline is placed between the beginning of the line and where the error/warning actually begins. See the screenshot:

<img width="618" alt="screen shot 2016-03-02 at 17 54 34" src="https://cloud.githubusercontent.com/assets/2621975/13475296/cd3af526-e0a0-11e5-90d4-f01b0fab5e6a.png">

Running Atom 1.5.3 on Mac OS X 10.11.3
linter@1.11.3
linter-js-standard@3.2.1

**Comment by steelbrain** [comment]
This is a bug in `linter-js-standard`, please re-open this issue there :)

**Comment by gabmontes** [comment]
Thanks @steelbrain! Will do.
