### ISSUE TITLE
Support proselint

### ISSUE THREAD

**Issue by StevenACoffman** [atom-community/linter#1094]
[proselint](https://github.com/amperser/proselint) is a lovely command line utility that would be very nice to support in Atom Linter. There is an open issue https://github.com/amperser/proselint/issues/36 over there, but this issue is to keep track of it here. The ProseLint people don't really have anyone familiar with atom linter over there.

**Comment by steelbrain** [comment]
Creating a linter package is easy, I'd be happy to help one create it by reviewing. Checkout the docs on how to create it https://github.com/atom-community/linter/wiki/Linter-API

**Comment by smockle** [comment]
Hi! I published my initial attempt at displaying `proselint` results in Atom Editor: https://atom.io/packages/linter-proselint. @steelbrain, if you have time, a review would be greatly appreciated—I’ve never used the atom-linter API before.

**Comment by steelbrain** [comment]
@smockle Thanks for creating that package! I have submitted a PR with minor enhancements here https://github.com/smockle/linter-proselint/pull/2

**Comment by florianb** [comment]
:clap: Good work everybody! :candy:
