### ISSUE TITLE
Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by cblp** [atom-community/linter#1095]
```
Error: Missing html/text field on Linter Response
    at ~/.atom/packages/linter/lib/validate.coffee:40:19
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (~/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (~/.atom/packages/linter/lib/message-registry.js:36:16)
    at ~/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ~/.atom/packages/linter/lib/linter-registry.js:66:26
```

```
$ apm list --installed --bare
autocomplete-haskell@0.6.2
haskell-ghc-mod@1.10.1
highlight-selected@0.11.2
ide-haskell@1.5.3
ide-haskell-stack@0.0.3
language-haskell@1.7.2
linter@1.11.3
linter-hlint@0.4.3
linter-pylint@1.2.0
```

JS console is empty.

Looks like haskell-ghc-mod returned somthing wrong. But what?

**Comment by steelbrain** [comment]
This is not a problem in linter but your linter provider, please open an issue there :)

**Comment by cblp** [comment]
@steelbrain No, it is a problem in linter, triggered by problem in lint provider.

The problem is that linter shows obscure error message.

**Comment by steelbrain** [comment]
Well, I am afraid you are misinformed my friend, here is what happens when this error is triggered

1. You edit or save the editor
2. Linter notifies all of the providers and asks the providers for messages
3. Linter validates all the messages received from the providers for any errors
4. If there's an invalid message, linter throws this error that you're seeing

**Comment by cblp** [comment]
This is right. But wouldn't it be nice if linter would show any information about origin of the error? For example, the name of provider that gave response without html/text.

**Comment by steelbrain** [comment]
It has already been fixed in master, it now shows the linter provider, as well as the error object and a correct trace

**Comment by cblp** [comment]
Thank you!
