### ISSUE TITLE
Jump to previous error

### ISSUE THREAD

**Issue by jordwalke** [atom-community/linter#1096]
Is there no hook for jumping to the previous error? Is there a way to only jump forward/backward for errors in the current file?

**Comment by steelbrain** [comment]
It's not really recommended to use these jump APIs, we recommend you use the panel

**Comment by jordwalke** [comment]
But many people do not use the mouse or have trouble using the mouse.

**Comment by steelbrain** [comment]
They must have a touchpad. If they don't have a touchpad then I wonder how they use their operating system.

**Comment by jordwalke** [comment]
Via the keyboard or voice commands. Accessibility is actually a very big deal - a ton of effort goes into it for virtually every application that matters (and rightfully so - it has many benefits beyond just allowing a wider set of people to use your software).

**Comment by steelbrain** [comment]
Fine. These commands have been removed from this package btw. Can you reopen this at [`linter-ui-default`](https://github.com/AtomLinter/linter-ui-default)?

**Comment by AsaAyers** [comment]
@jordwalke fyi, @steelbrain owns the whole project now. Without warning he transferred the repo out of https://github.com/atom-community/Linter which gives him absolute unchecked control over this project.

@steelbrain Just because I have a mouse doesn't mean it's ever acceptable for it to be the only option to do something. I use vim mode in atom because it allows me to spend virtually all of my time on the keyboard. Full time professional developers understand the dangers of RSI and the need to not have to touch the mouse constantly.

**Comment by steelbrain** [comment]
@AsaAyers I would appreciate if you didn't involve politics into the bug reports :\

**Comment by AsaAyers** [comment]
I already fixed this issue, but @steelbrain refused to merge it. So now I have to run my own fork and update periodically.

**Comment by steelbrain** [comment]
@AsaAyers best of luck running your fork, but we fixed it properly instead of monkey patching it. 

Commands were implemented in `linter-ui-default` by https://github.com/steelbrain/linter-ui-default/pull/56

**Comment by steelbrain** [comment]
Another important thing to note is that commands are a first-class citizen in `linter-ui-default` and are recommended to add to your keymap to make them fit in your workflow.

**Comment by AsaAyers** [comment]
That's nice, but do I have to wait until you finish this round of re-implementing linter before I can use it?

**Comment by steelbrain** [comment]
I am not reimplementing linter, it's just a few things unimplemented in [`linter-ui-default`](https://github.com/steelbrain/linter-ui-default/issues). We really hope to ship it in the next few weekends

**Comment by steelbrain** [comment]
In case you don't want to wait and want to be the Early Bird, the installation instructions are in the repo README :)

**Comment by AsaAyers** [comment]
btw, the politics of linter aren't irrelevant. If people want to be involved in the project I think it's important to know that it's run by an iron-fisted dictator and is in no way managed by a community. There is no one to appeal to on disagreements with you, you stole sole access to everything.

**Comment by steelbrain** [comment]
Don't you have something else to do? I really don't want to spend the next few hours arguing with someone who doesn't know what he's saying

**Comment by AsaAyers** [comment]
What exactly am I wrong about? I've been here from the beginning and I know exactly what's going on. I'm also a full time developer who has issues when I get stuck working on some crappy thing that causes me to reach for the mouse constantly. I have an arm brace I need to wear occasionally for that exact reason.

**Comment by steelbrain** [comment]
Also when you say that I `stole access to everything` you are misguiding the gentlemen subscribed to the repo/issues. I have been developing this from day 1, and I still am, I did not steal anything. I just rearranged a few things for the better future of the project. If anyone has any doubts, they should look at the graphs tab github provides for repos. and Please, do not try to talk to me politically on github issues as to save the reader's time I will be deleting those pointless comments.

GitHub issues are strictly for issues, they are not something that people subscribe for to get comments about some private drama. If you have any contribution, show us and we'll discuss about it being merged. At the end of the day I want what's best for the project.

The problem you are trying to address has already been fixed. We have not removed any access from the keyboard users. We have already added commands that you can bind to any of your key and that is exactly what was being demanded. It's time you stopped nagging and started thanking us for putting our time into this project which we do for free :)

**Comment by AsaAyers** [comment]
Should such conversation be moved to slack where you can't delete and hide my comments?

http://atom-slack.herokuapp.com/

**Comment by steelbrain** [comment]
I have no interest in continuing this conversation because the bug it represents has been fixed. It isn't closed as invalid or anything, it is **fixed**. I am not sure how difficult it is to understand that :)
