### ISSUE TITLE
Selectable/highlightable messages

### ISSUE THREAD

**Issue by bmhkim** [atom-community/linter#633]
I've been mildly annoyed by Linter's un-selectable messages. It would be nice to be able to copy and paste them to search for codes or help in identifying/fixing problems that the linter is pointing out.

**Comment by steelbrain** [comment]
We've been getting that feature request for some time.

**Comment by bmhkim** [comment]
I tried searching for this, so my apologies if it's duplicative....

**Comment by k2b6s9j** [comment]
I know that Linter 0.x had a copy button on it's messages. We could reimplement that.

**Comment by steelbrain** [comment]
@k2b6s9j `-webkit-user-select: text` we don't need a button to allow users to copy directly, a button to just select would be cool

**Comment by steelbrain** [comment]
wanna take this one?

**Comment by k2b6s9j** [comment]
I got you.

**Comment by k2b6s9j** [comment]
Do we want both bubbles and panel highlightable, or just the panel?

**Comment by steelbrain** [comment]
Both would be ideal.

**Comment by k2b6s9j** [comment]
Can do.

**Comment by steelbrain** [comment]
Also I've updated my initial comment, we don't need a button to do it, we just need to allow the user to select it.

**Comment by iam4x** [comment]
@steelbrain I find the button really straightforward, I will disagree with only selectable.

**Comment by steelbrain** [comment]
@iam4x the UI space comes at a premium, we must try to save it as much as we can. so here's me :-1: on the button.

**Comment by simurai** [comment]
Yeah, strange.. if I drag+drop the `<div id="linter-panel">` just under the `<body>`, I can select the text but copying (cmd-c) still doesn't work.

![copy](https://cloud.githubusercontent.com/assets/378023/8511080/b7a9bfc4-2342-11e5-8e81-ff610a7e117f.gif)

Is there a "prevent default" somewhere.

**Comment by steelbrain** [comment]
@simurai Copying doesn't work because atom doesn't do that on whole body by default, we'll have to use `electron`'s `clipboard` module in the core somewhere.

**Comment by simurai** [comment]
Ok, more strange things.. if I add a tabindex, I can select the text. `<div id="linter-panel" tabindex="1">`.

Or it also works if I do a `display: none` on the `atom-pane-container` above.

**Comment by steelbrain** [comment]
:sweat_smile:

**Comment by steelbrain** [comment]
Moved to https://github.com/mdgriffith/atom-inline-messenger/issues/2
