### ISSUE TITLE
Warnings have greater visual precedence than errors

### ISSUE THREAD

**Issue by bjmiller** [atom-community/linter#653]
If you have both a working and an error on the same line, the gutter dot is warning-colored instead of error-colored.  I would expect errors, begin of greater severity, to take precedence in notifications.  It seems to color the dot based on whichever issue is first, be it warning nor error.

This is pretty low priority, but I thought that I should at least bring it up.

**Comment by steelbrain** [comment]
We don't really order errors according to severity and then push them on the gutter and stuff. Marking as a feature request.

**Comment by steelbrain** [comment]
Moved to https://github.com/mdgriffith/atom-inline-messenger/issues/3
