### ISSUE TITLE
Display which linter is reporting the error

### ISSUE THREAD

**Issue by artoale** [atom-community/linter#665]
Hey! First thing, thanks for the awesome work - amazing stuff!
Now, after some recent update (which massively changed the UI) I'm no longer able to see which linter raises an error/warning messages. This is quite troublesome, since I use e.g. gjslint, jscs and  at the same time - and I can't distinguish which error is raised by which linter. 

This is particularly needed when working on projects where one "linter" has to be enforced, while other are used only for personal sanity :)

**Comment by steelbrain** [comment]
We have it planned already for api `v1.1.0`

**Comment by artoale** [comment]
Whoohoo! Thanks!

**Comment by steelbrain** [comment]
Assigning to Kelper; 'cause he said he wanted to do the next providers API

**Comment by k2b6s9j** [comment]
Yeah. I'll start work on Monday.

**Comment by steelbrain** [comment]
Merged into https://github.com/atom-community/linter/issues/763
