### ISSUE TITLE
Don't assume exit code 8 means missing linter binary

### ISSUE THREAD

**Issue by voxpelli** [atom-community/linter#670]
## The problem

Currently the exit code `8` when running a linter is always assumed to mean that the linter binary couldn't be found.

These are the related lines (link goes to latest commit as of this writing to ensure correct line numbers):

```coffeescript
if exitCode is 8
  # Exit code of node when the file you execute doesn't exist
  return @linterNotFound()
```
https://github.com/AtomLinter/Linter/blob/d4827d6e5d49c9e8e09fced27afe6dde703f6fad/lib/linter.coffee#L172-174

The exit code `8` seems to be the exit code that Node uses for any kind of crash though – not just crashes because the node-binary couldn't find the file to execute (which I think is what caused this code to be implemented in the first place) but also any other kind of crashes.

I just ran into the category of _"other kind of crashes"_ when I used [linter-jshint](https://github.com/AtomLinter/linter-jshint) and the JSHint binary crashed due to what I reported there as: https://github.com/jshint/jshint/issues/2506

It was very confusing to get that crash within JSHint reported as if the JSHint binary could no longer be found. I tried lots of different JSHint paths and it wasn't until I dug into the Linter code and started logging stuff that I found out that it was actually not at all the binary that had gone missing, but rather a bug in the binary that had it start crashing.

## The proposed solution

I would propose doing one of the following:

1. Either always report exit code `8` as a crash rather than a missing binary...
2. ...or detect the error message from the node binary when the node binary can't find the file its looking for and use that to still report those exit code `8` errors as missing binaries and make the rest of exit code `8` errors be reported as crashes.

**Comment by steelbrain** [comment]
Ouch

**Comment by k2b6s9j** [comment]
This is also a legacy issue.

**Comment by steelbrain** [comment]
Closing as it's a legacy API issue and linter-jshint has already upgraded to the latest one.
