### ISSUE TITLE
Add setting to specify "scope" of status bar indicator (file/project)

### ISSUE THREAD

**Issue by caleb531** [atom-community/linter#683]
## What?

Add an settings option to limit the "scope" of the status bar indicator and "Next Error" command to either file or project.

## Why?

I prefer to work on a file-by-file basis while linting, and thus use the Line tab to show only errors/warning for the current line within the bottom panel. I can then use the Linter status bar indicator ("X errors") or my trusty key binding to move to the next error in the file.

However, as I was working on two separate files (the first had errors, the second did not), clicking the status indicator (or triggering my key binding) when in the file *with no errors* brought me to the file *with errors*. I also noticed that when viewing the file *with no errors*, the status indicator showed that there were errors (because I had the other file—the one *with* errors—open and inactive. This indicated to me that the status bar icon (as well as the "Next Error" command) works at the project level. Therefore, I would very much like an option to limit the scope of this to the current file only.

I hope that all makes sense. Please feel free to ask me for clarification.
Caleb

**Comment by steelbrain** [comment]
I think we had this option initially. but was removed 'cause no one wanted it. Votes people?

**Comment by iam4x** [comment]
Make sense for me.

**Comment by steelbrain** [comment]
I think I am gonna do this one

**Comment by iam4x** [comment]
I will use it for sure :+1: Thank's for spending so much time on the project @steelbrain

**Comment by steelbrain** [comment]
Pleasure :bow:
