### ISSUE TITLE
Linter: Toggle doesn't clear issues

### ISSUE THREAD

**Issue by Eschon** [atom-community/linter#716]
![clearerrors](https://cloud.githubusercontent.com/assets/11647830/8589594/55fe640e-2618-11e5-8e09-c2bb96dea4f2.gif)

As shown in the gif when I toggle the linter the counter in the bottom bar stays the same until I switch the window. This is not that big of a deal but I thought I'd just report it anyway.

**Comment by steelbrain** [comment]
Thanks for the bug report!

**Comment by Eschon** [comment]
Wow that was fast.
Thanks for the fix :clap:

**Comment by Eschon** [comment]
I tried the new release and somehow this problem still exists.

**Comment by steelbrain** [comment]
Ouch, I had confirmed that the fix above works, I'll try to repro again when I have some time

**Comment by iam4x** [comment]
I confirm that the bug is still preset, re-opening.

**Comment by steelbrain** [comment]
Are you able to reproduce this on #738

**Comment by steelbrain** [comment]
Merging into https://github.com/atom-community/linter/issues/748
