### ISSUE TITLE
Error panel is no longer collapsable

### ISSUE THREAD

**Issue by alkamin** [atom-community/linter#722]
Atom 1.02, Linter 1.2.3, Win7

Clicking on the currently selected tab (File, Project) no longer collapses the error panel.  The only way to hide the error panel is to disable it via the settings.

I used this feature all the time, as I prefer not to have the error panel changing sizes all the time while trying to type, but appreciated being able to click a tab to have it expand into view when I needed to see the linting messages.

**Comment by steelbrain** [comment]
Ouch.

**Comment by nemoDreamer** [comment]
:+1: especially when viewing large files that aren't under your control (dependency sources, etc), 60+ errors will lead to a hidden editor, and needing to disable the panel altogether in settings. The chrom of the panel is even not selectable, since it drops off the page, so I don't think a click on a tab should be the only way to toggle it: maybe by clicking on the "x issues" in the status bar?

**Comment by steelbrain** [comment]
@nemoDreamer We also have a command for this by the way, you can assign it to your favorite key and just press it to toggle until we fix this

**Comment by nemoDreamer** [comment]
:laughing: thanks, @steelbrain, i _just_ figured out that toggle is per editor. Cool!

**Comment by steelbrain** [comment]
There's also a `togglePanel` :wink:

**Comment by nemoDreamer** [comment]
No. Way.

Btw, **LOVE** how active this repo is!

**Comment by steelbrain** [comment]
Awww, Thank You :bow:

**Comment by nemoDreamer** [comment]
Woot! :lollipop:

**Comment by nmccready** [comment]
Where is this error panel setting? Mine is no longer showing and I am trying to figure out how to resurrect it.

**Comment by steelbrain** [comment]
@nmccready Just click the active tab in the bottom panel or enable `Show Bottom Panel` config

**Comment by nmccready** [comment]
@steelbrain can you take a screen shot? I am not seeing this on my instance of atom.

**Comment by steelbrain** [comment]
@nmccready  ![settings](https://cloud.githubusercontent.com/assets/4278113/12038482/c4750390-ae15-11e5-9f7e-a16a6a96ee30.png)

**Comment by nmccready** [comment]
So yeah I totally do not have this at all. Maybe a bug but this feature is entirely missing in my aotm.

1.3.2 OSX

**Comment by steelbrain** [comment]
@nmccready normally this fixes it
```
$ apm uninstall linter
$ apm install linter
```

**Comment by nmccready** [comment]
ahh found it thanks. I was in the wrong part of settings.
