### ISSUE TITLE
$PATH is not available on OSX when not launched from CLI

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#726]
Ideas people?
I had thought of parsing `~/.bashrc` or similar of users to extract the values ourselves but that doesn't seem like the best solution.

**Comment by steelbrain** [comment]
Resuming from https://github.com/AtomLinter/Linter/issues/150 and https://github.com/AtomLinter/linter-jshint/issues/120

**Comment by steelbrain** [comment]
Can someone try this and see if it works? https://github.com/sindresorhus/fix-path

**Comment by iam4x** [comment]
@steeelbrain We may need to use `BufferedNodeProcess` from atom to run CLI linters.

**Comment by steelbrain** [comment]
@iam4x how does the buffered process solve this? does it support stdin?

**Comment by adarhef** [comment]
I just tried installing fix-path but I don't know how to actually use it, or whether simply installing it is sufficient. After running 'npm install --save fix-path' and reinstalling linter-jshint I still get the error.

**Comment by steelbrain** [comment]
@adarhef You will not just have to save it there, but will also have to modify the activate function to invoke it like
```
activate: ->
    require('fix-path')()
```

**Comment by adarhef** [comment]
After adding it the result of 'console.log(process.env.PATH)' on my setup is '/usr/bin:/bin:/usr/sbin:/sbin'

Is that what you'd expect? I'm still getting the error.

**Comment by steelbrain** [comment]
Ahh :( so we will have to try something else then

**Comment by b52** [comment]
This is not a problem of Atom or any other app, but how Mac OS X handles environment variables for CLI and GUI applications.

In order to update the environment variables for GUI applications without launching them from the shell to inherit the parents environment, you have to explicitly set them using `launchctl`.

E.g., to make your shells `$PATH` the default `PATH` for all GUI applications for the current session, just execute the following:

```bash
$ launchctl setenv PATH "$PATH"
```

A quick Googling should provide you with enough information how to do that on each login.

**Comment by fburleigh** [comment]
I got here from an AtomLinter/linter-jshint issue about Atom's console showing:

    Uncaught Error: write EPIPE 
    JSHint Result

on opening any JS file.  In other words, linting JS files using the "bundled" JS linter fails.

Facts: Atom 1.0.4, linter-jslint is 1.04, linter is 1.2.3. I open Atom from the CLI on OS X 10.10.4.

**Comment by nguyengiangdev** [comment]
Try use Atom from CLI it work for me.
My env: Atom 1.0.2, mac os el capitan beta 3, linter-jshint 1.0.4.

**Comment by fburleigh** [comment]
Alas, run from *my* command line, Atom's linter-jshint fails. I erred above: my Atom is 1.02. So except for OS X, we seem to have the same software. And I use the "bundled" jshint -- that is, I do not have an external JS linter so have not set a path to one.  I think that is ok.

**Comment by rldona** [comment]
I've found a way to fix it.

1. Atom
2. Open Your Init Script
3. Add the following line:

process.env.PATH = ["/ usr / local / bin" process.env.PATH] .join (":")

4. Restart Atom.

That is all. Now everything works correctly :)

![captura de pantalla 2015-07-12 a las 0 44 41](https://cloud.githubusercontent.com/assets/1206870/8635663/3aa08f66-282f-11e5-9b17-896b6f3553f1.png)

**Comment by jackhsu978** [comment]
@rldona your workaround works for me! thank you!

**Comment by AlexKvazos** [comment]
@rldona Thank you for that work around.

**Comment by animecyc** [comment]
Was having the same problem, I use `nvm` and `rbenv` so I need their respective scripts executed before I can use anything; The below worked just fine for me, I am using bash (and bash_profile), you can just swap in what you need...

```javascript
childProcess = require('child_process');

process.env.PATH = String((
  childProcess.execFileSync(\
    process.env.SHELL,
    ['-c', 'source $HOME/.bash_profile; echo $PATH']
  )
)).trim()
```

**Comment by nguyengiangdev** [comment]
@rldona thank you, that works for me.

**Comment by zieglar** [comment]
@rldona Thank you!

**Comment by ketamin** [comment]
@rldona Is there a way to use your fix on Ubuntu 15.04? Because adding your line into the init.coffee don't seem to work for me.

**Comment by gmcinalli** [comment]
@rldona Thanks for your workaround!

**Comment by viettrung9012** [comment]
@rldona Thanks your workaround fixes the problem on my computer

**Comment by steelbrain** [comment]
@animecyc Your solution is a clever one!

**Comment by ebordeau** [comment]
@rldona's workaround worked for me! Thanks!

**Comment by steelbrain** [comment]
Since this affects so many people, I've thought to workaround this issue somehow in [helper module][1], which is what the new transitioned linters use to spawn processes. We could extend what @animecyc suggests and get the value of `$PATH` on startup and use it for the session. 

Also, what shell types do you guys use? Let us know so we add it's support in the PATH extraction.

[1]:npmjs.org/package/atom-linter

**Comment by stdavis** [comment]
@rldona work around works for me as well. Thanks!

I use a bash shell.

**Comment by THPubs** [comment]
This bug also affects Linux. I just updated to the latest version which should have fixed the issue in OSX. But in Linux the bug is still there!

**Comment by steelbrain** [comment]
@THPubs If you're on linux and this bugs affects you, Then it means that you have a misconfiguration somewhere, because it's OSX's nature not to pass `$PATH` to apps run from GUI, Linux doesn't have this nature.

**Comment by THPubs** [comment]
@steelbrain Hmmm but it worked earlier. But recently stopped. Not sure whether it's after an atom update or a linux package update. Where should I look for the issue? :-)

**Comment by ketamin** [comment]
@steelbrain I am on Ubuntu 15.04 and this bug is affecting me too. Like I wrote above, the workaround didn't fix it for me.

**Comment by gggritso** [comment]
I use Fish shell, so I'd love to see it supported :)

**Comment by steelbrain** [comment]
That workaround will only work if you have your binaries in `/usr/local/bin`, If you have them in another folders like `/home/steel/.rvm/something/bin` then You'll need to add them there.

**Comment by MatiMenich** [comment]
@rldona Thank you!

**Comment by andersryanc** [comment]
I don't get it, why do you have to reference the system path for this? I thought it was included in the atom package itself, so you don't have to use the global / system one.

**Comment by wouldgo** [comment]
Got the same problem here on a linux machine. I installed node with `nvm` putting 

```
childProcess = require('child_process');
path = String(childProcess.execFileSync(process.env.SHELL, ['-c', 'export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; echo $PATH']))
process.env.PATH = path.trim()
```

in my `init.coffe` resolved the issue (basically I ran the same script that adds the nvm path in bash).

**Comment by RiFi2k** [comment]
Install it globally instead of locally -g

**Comment by none-da** [comment]
None of the above solutions worked for me :'(

**Comment by none-da** [comment]
> I've found a way to fix it.
> 
> Atom
> Open Your Init Script
> Add the following line:
> process.env.PATH = ["/usr/local/bin", process.env.PATH].join(":")

@rldona That did the trick for me. Thanks :+1:

**Comment by Jarema** [comment]
@rldona Your solutions works! Thanks. :+1:

**Comment by miguskar** [comment]
@animecyc Thanks for this!

**Comment by THuRStoN** [comment]
@wouldgo your fix work perfectly with nvm!

**Comment by iam4x** [comment]
@steelbrain Using `BufferedNodeProcess` from Atom is doing the work for me.

**Comment by johnschult** [comment]
@rldona :+1: Works great, thanks!

**Comment by devmao** [comment]
@wouldgo grazie1000!

**Comment by xxsnakerxx** [comment]
If you have .jshintrc file in a folder, errors still appears...

**Comment by dgautsch** [comment]
To get around this issue I've been launching atom from the command line as sudo `sudo atom .` I have a .jshintrc in my folder and have not noticed any problems.

**Comment by jcgertig** [comment]
None of this fixes it for me not even launching from cli

**Comment by steelbrain** [comment]
@iam4x I don't really see anything magical in https://github.com/atom/atom/blob/master/src/buffered-process.coffee

**Comment by steelbrain** [comment]
(wrong button)

**Comment by nemoDreamer** [comment]
:+1:
I'm sorry, but for all the talk of (admittedly clever) work-arounds, or it being "the user's fault" as per @b52, this worked fine before the update, and now no longer does. Other Atom plug-ins use CLI's with no trouble, so there needs to be an out-of-the-box solution that does not involve your shell profile or init script...

**Comment by steelbrain** [comment]
@nemoDreamer I am not sure how it was working before the update and how the other plugins are working, the error is quite obvious and not a package author's fault :sweat_smile:

**Comment by jcgertig** [comment]
What to do then when none of the options given work

**Comment by steelbrain** [comment]
@jcgertig do `which jshint` or the path of the linter you are trying to use and replace `/usr/local/bin`in @rldona's solution with it's folder

**Comment by jcgertig** [comment]
I did 
```js
  childProcess = require('child_process');

  process.env.PATH = String(
    childProcess.execFileSync(
      process.env.SHELL,
      ['-c', 'source $HOME/.bash_profile; echo /Users/jonathangertig/.nvm/v0.10.38/bin/jshint:$PATH']
    )
  ).trim()

  console.log("PATH: ", process.env.PATH);
```

and no such luck

**Comment by jcgertig** [comment]
it actually seams to run after the plugins start could that be an issue?

**Comment by steelbrain** [comment]
```
process.env.PATH = ["/Users/jonathangertig/.nvm/v0.10.38/bin", process.env.PATH].join(":")
```
@jcgertig ^ try that one. and No it doesn't matter if it's executed before or after.

**Comment by jcgertig** [comment]
interesting thanks

**Comment by matwood** [comment]
I'm getting the errors, but the linter appears to still be working. I have a complete path to jshint defined in the configuration.

**Comment by steelbrain** [comment]
@matwood which linter is reporting it for you?
and the recent updates have been showing them, they were there before the updates.

**Comment by proehlen** [comment]
Er, what's actually worst for me than the linter not working is the massive (on my laptop) and distracting message every time I type something in the editor.  
![image](https://cloud.githubusercontent.com/assets/8384068/8695673/b4ee0382-2b10-11e5-8e40-ee34187ace88.png)
I'm going to have to uninstall the package -  otherwise, I'd leave this package installed and expect a future update would resolve the issue.  None of the fixes in this thread worked for me btw.

**Comment by matwood** [comment]
@steelbrain I do not know if it was the latest update, but it was working pre 1.0. The linter throwing the error for me is JSHint like @proehlen above.

**Comment by siancu** [comment]
I am getting the exact same result. The message in the console is empty. However the error is "Syntax error: Unexpected end of input"

**Comment by siancu** [comment]
The workaround from @rldona worked for me.

**Comment by Adam-Moss** [comment]
I get the same issue as @proehlen, and the workaround provided by @rldona doesn't work, Mac OS 10.10.4.  Having put console.log calls into a bunch of coffee scripts I'm fairly sure the path is actually correct:

<img width="1252" alt="screen shot 2015-07-15 at 16 33 11" src="https://cloud.githubusercontent.com/assets/2951486/8702402/761f8e06-2b0f-11e5-8eca-ea5d5ea2eaa3.png">

And the error crops up after the call to stdin.end().  Occasionally it gives an "uncaught exception,  failed to write to EPIPE" message.

**Comment by acusti** [comment]
Similarly to @Adam-Moss, I get `Uncaught Error: write EPIPE` as the error in the console, triggered by `~/.atom/packages/linter-jshint/lib/main.coffee:41`.

The “Invalid Result recieved from JSHint” notification referred me here, but I don’t think it’s actually the same problem as described earlier in this issue.

**Comment by jluchiji** [comment]
Workaround suggested by @rldona worked for me. I added the following to my init script:
```
process.env.PATH = ["/usr/local/bin", process.env.PATH].join(":")
```
P.S. I am using OS X 10.10

**Comment by erikmellum** [comment]
My pain regarding this issue can be located here: https://discuss.atom.io/t/not-able-to-spawn-npm-modules-from-electron-package-in-os-x-solved/18905

The TL;DR is here:

```
gulp=spawn(process.env.SHELL, ['-c', 'cd ' + project.directory + ' && gulp'])
``` 
instead of
```
var gulpPath = path.join(__dirname, '../', 'node_modules', 'gulp', 'bin', 'gulp.js');
gulp=spawn(gulpPath, {cwd: project.directory});
```

And fixPath for anything else like this:
```
process.env.PATH=childProcess.execFileSync(process.env.SHELL, ['-i', '-c', 'echo $PATH']).toString().trim()
```

**Comment by steelbrain** [comment]
Can someone confirm that this fixes it? like @erikmellum suggested.
```js
childProcess = require('child_process')
process.env.PATH = childProcess.execFileSync(process.env.SHELL, ['-i', '-c', 'echo $PATH']).toString().trim()
```

**Comment by jackhsu978** [comment]
@steelbrain that does not work for me. I'm on OS X 10.10

**Comment by steelbrain** [comment]
Closing in favor of https://github.com/atom-community/linter/issues/743

**Comment by halhenke** [comment]
@nemoDreamer +1000 - people shouldnt be hacking around their init scripts to fix this - something seems to have changed/broke in the past release or two

**Comment by steelbrain** [comment]
@halhenke We did not change anything like that in the past few releases. The error is quite obvious that OSX apps that are run from the GUI don't have **any** info about the global `$PATH`.
and about the people experiencing these issues on other platforms, I am using Ubuntu 15.04 GNOME edition, I am unable to reproduce this behaviour and haven't seen it even once in my life, my guess is that it could be because of a user misconfiguration.

**Comment by lmartins** [comment]
I had the plugin working for a long, long time. These errors started to show just a few days ago.

**Comment by steelbrain** [comment]
What linter provider are you using and what's the path to the CLI one? and what's the value of `process.env.PATH` in your atom dev tools?

**Comment by victorleungtw** [comment]
Thanks @rldona, it works:)

**Comment by bitIO** [comment]
@steelbrain that worked for me on OSX 10.10. Thanks @erikmellum

**Comment by Erossek** [comment]
Is there any solution how to fix this error on Windows OS?

**Comment by steelbrain** [comment]
@Erossek On windows, You should add the linter folders to your Environment Variables.

**Comment by Alex0007** [comment]
@steelbrain 
> I am using Ubuntu 15.04 GNOME edition, I am unable to reproduce this behaviour and haven't seen it even once in my life, my guess is that it could be because of a user misconfiguration.

I am using Ubuntu 15.10 (alpha) and iojs installed with nvm and im getting these errors

**Comment by steelbrain** [comment]
@Alex0007 have you added `io.js` bin path to your `$PATH`?
What's the result of `echo $PATH` in a terminal. My guess is You haven't added it to your `$PATH`, and You should to fix this error. or alternatively, add absolute path to the linter in your provider config.

**Comment by Erossek** [comment]
@steelbrain Your explanation was not detailed enough for me to solve my problem. Probably I misunderstood you. What I did is:
I have added this path "C:\Users\KLIMCZAKK\.atom\packages\linter\node_modules\grim\node_modules\coffeestack\node_modules\coffee-script\bin\" (this was the only "bin" directory) to my Environment Variable "Path", but it did not change anything, I still have an error :(

**Comment by steelbrain** [comment]
The `Path` needs to be completely uppercase, and You don't need a trailing slash there.
You can confirm your changes by running `coffeelint` from cmd, if it works there, It'll work in atom.

**Comment by Alex0007** [comment]
@steelbrain 
```
echo $PATH
/usr/local/heroku/bin:/home/alex0007/.nvm/versions/io.js/v2.3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

![](http://i.imgur.com/swOy43B.png)

**Comment by steelbrain** [comment]
@Alex0007 what's the value of `process.env.PATH` in your atom dev tools?

**Comment by Alex0007** [comment]
@steelbrain 
```process.env.PATH
"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"```

**Comment by steelbrain** [comment]
Aaha! You are adding that path to your env using an unrecommended method I believe, the way I add stuff to my `$PATH` on ubuntu is by having something like this in my `.bashrc`
```
export PATH=$PATH:/steel/Local/android-sdk-linux/tools:/steel/Executables:/steel/Local/io.js/bin
```

**Comment by Alex0007** [comment]
@steelbrain 
With nvm thats way of setting PATH requires everytime updating file on io.js updates.

It's simpler for me to start Atom from shell. Thanks!

**Comment by steelbrain** [comment]
@Alex0007 by the way, If you could investigate where `rbenv` includes it's config file, You could simply import that file in your `.bashrc`, so You won't have to update your `.bashrc` every time you use `nvm`

**Comment by daverogers** [comment]
Can someone confirm that this fixes it? like @erikmellum suggested.
```javascript
childProcess = require('child_process')
process.env.PATH = childProcess.execFileSync(process.env.SHELL, ['-i', '-c', 'echo $PATH']).toString().trim()
```

This did not work for me either. Mac OSX 10.10.4.

**Comment by animecyc** [comment]
@daverogers Have you tried [my approach](https://github.com/atom-community/linter/issues/726#issuecomment-120784588)? Swap in what you need to source. This works for me using `nvm` and `rbenv`.

**Comment by dgautsch** [comment]
@steelbrain my process.env.PATH is `process.env.PATH
"/usr/bin:/bin:/usr/sbin:/sbin"` Am i having the same issue as Alex007? I don't recall modifying my bashrc recently.

**Comment by steelbrain** [comment]
@dgautsch mind posting your custom part of `.bashrc` with the private info removed?
Here's mine https://github.com/steelbrain/Helpers/blob/master/.bashrc

**Comment by dgautsch** [comment]
.bashrc
```
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias ls="ls -GFlash"
```

.bash_login
```
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
```

**Comment by steelbrain** [comment]
What's your path to rbenv file? Can you add
```
. /path/to/rbenv
```
and then restart atom and dump the value of `process.env.PATH`

**Comment by Alex0007** [comment]
@animecyc your approach doesn't work for nvm, 
There is no .bash_profile file. Sourcing .bashrc does not help

but @wouldgo approach works

**Comment by dgautsch** [comment]
@steelbrain `which rbenv` returns nothing. I don't have it installed.

**Comment by pablocarreraest** [comment]
some help with this error! it was working alright then form one day to another this error message happens every time I write.
<img width="470" alt="screen shot 2015-07-17 at 4 50 04 pm" src="https://cloud.githubusercontent.com/assets/4999086/8757905/f8ae2b62-2ca3-11e5-8ea7-d0cb3123ab45.png">

**Comment by steelbrain** [comment]
@pablocarreraest Yep, that's an issue with jshint, You can workaround this by installing node, or wait a little bit till we fix it.

**Comment by pablocarreraest** [comment]
ok! I have already installed node (v0.12.7)! I will wait then! hope the best.

**Comment by adambuczynski** [comment]
For late comers like me, @rldona 's [workaround](https://github.com/atom-community/linter/issues/726#issuecomment-120666636) worked well for me, as did starting atom from the command line.

**Comment by daverogers** [comment]
@animecyc - nope, it did not work. `.bash_profile` includes NPM in export_path - what Node package specifically does JSHint actually need? (I installed Node through Homebrew, is that why some above solutions work for others but not for me?)

**Comment by steelbrain** [comment]
Be advised jshint people, I have just released a fix and it should work for people who don't have node installed and are not on OSX.

**Comment by Adam-Moss** [comment]
@steelbrain works for me on OSX too!  Many thanks!!! :+1:

**Comment by steelbrain** [comment]
Ah right, it should work on OSX too, since we're using bundled jshint instead of the global one.

**Comment by buschtoens** [comment]
Also happens on Windows 8.1.

**Comment by steelbrain** [comment]
@buschtoens do you mean that the error is there on windows 8.1 or the error was fixed in windows 8.1?

**Comment by buschtoens** [comment]
The error is there. Exactly this one:

![](https://cloud.githubusercontent.com/assets/4999086/8757905/f8ae2b62-2ca3-11e5-8ea7-d0cb3123ab45.png)

**Comment by steelbrain** [comment]
@buschtoens can you confirm that you updated to the release I pushed a few hours ago?

**Comment by buschtoens** [comment]
@steelbrain My bad. I did the update but did not restart Atom. Restarting solved it.

**Comment by steelbrain** [comment]
Glad to know the fix was cross-platform!

**Comment by buschtoens** [comment]
Awesome work. :gem:

**Comment by fburleigh** [comment]
@saschagehlich I always start Atom from the OS X CLI, and had also implemented the temporary workaround init script fix, with no love. Your change to linter-jshint 1.1.1 has fixed all that. Excellent -- thank you!

**Comment by restlessbit** [comment]
@steelbrain Thanks a bunch!

**Comment by robbiespeed** [comment]
Getting this error on fedora 21 with linter-jshint 1.1.2 and below. Even setting the path in the config doesn't work, but I only get the error if I have is a .jshintrc file in the project.

**Comment by steelbrain** [comment]
@robbiespeed would you mind opening an issue over to the linter-jshint repo?

**Comment by robbiespeed** [comment]
@steelbrain In the process right now.

**Comment by Ahmed-90** [comment]
still getting this on win 8.1 
Linter version: 1.2.4
JsHint: 1.1.2

**Comment by steelbrain** [comment]
@Ahmed-90 It's highly unlikely that jshint will produce this error because of this, can you open up a bug over to it's repo please?

**Comment by psko** [comment]
@steelbrain This issue trigger **everytime I open a JavaScript file**. Plus, I'm on **Windows 8.1**, nothing to do with OS X.

![jshint-issue](https://cloud.githubusercontent.com/assets/6703711/8773615/cb1a52dc-2ed5-11e5-90b8-c075e51257d1.jpg)


OS: Windows 8.1
Atom: 1.0.2
linter: 1.2.4
linter-jshint: 1.1.2

**Comment by filipesilva** [comment]
Same as @psko above. Very annoying bug.

**Comment by vbourgeois** [comment]
Same as @psko for me too...

**Comment by heyyoyo** [comment]
Same error on windows 7

**Comment by steelbrain** [comment]
JSHint people see https://github.com/AtomLinter/linter-jshint/issues/145#issuecomment-122872627

**Comment by stdavis** [comment]
Latest update fixed the issue for me on OSX. Thanks!

**Comment by dheerajvs** [comment]
Same as @psko for me on Windows 7 (plugin version 1.1.2)

**Comment by RanadeepPolavarapu** [comment]
Getting the same bug as @psko  on Windows 7 as well. Proper environment variables have been set and even then it is the same bug. Tried manually changing the executable path setting in the linter-jshint config.

**Comment by steelbrain** [comment]
@RanadeepPolavarapu see https://github.com/AtomLinter/linter-jshint/issues/145

**Comment by adambuczynski** [comment]
I've started getting this issue again on OS X unfortunately:

![ss](https://www.dropbox.com/s/m2dv43sue7558hc/Screenshot%202015-07-21%2011.11.07.png?dl=0)

This is with linter-jshint version 1.1.2.

**Comment by steelbrain** [comment]
For jshint users, I had to make a change that passes ENV from atom the the spawned linters, It fixed https://github.com/AtomLinter/linter-jshint/issues/140 but introduced https://github.com/AtomLinter/linter-jshint/issues/145
To fix this issue until we do, You can just downgrade helper version of jshint
```
cd ~/.atom/packages/linter-jshint
npm install atom-linter@2.0.0
```

**Comment by renestalder** [comment]
Just want to add, Atom pointed me to this issue here with the dialogs shown by all the other people. Anyway, I had wrong formating in my .jshintrc file. Fixing the syntax, removed the error. So first check if you are using a .jshintrc configuration and it hasn't any syntax errors.

**Comment by augbog** [comment]
Confirming that downgrading to `atom-linter@2.0.0` for Mac OS X 10.10.3 fixed the issue for me! Thanks @steelbrain !

**Comment by piotr-cz** [comment]
Like @renestalder i had an error in my .jshintrc file.
I suggest to change add to the message advising to check the .jshintrc file.

**Comment by aendrew** [comment]
A stray comma in `.jshintrc` throws the above error. I'd politely suggest improving that error message, it's fairly misleading.

**Comment by cloudbring** [comment]
@aendrew Making sure my .jshintrc is valid (without trailing commas) fixed it for me.

**Comment by steelbrain** [comment]
Here's an announcement for you, we have recently published a release of `atom-linter` (npm helper module for linter providers) that now automatically determines `$PATH` even if atom is not launched from terminal. Therefore all linters using it for execution will be working consistently from both dock and cli

**Comment by filipesilva** [comment]
Sweet. :+1:

**Comment by daverogers** [comment]
Thanks :+1:

**Comment by Arcanemagus** [comment]
Working on publishing updates to plugins that include this now :wink:.

**Comment by nemoDreamer** [comment]
Woooot! :lollipop:

**Comment by devkinetic** [comment]
Latest Version here, using El Capitan and ZSH. Having this issue with a few linters. Adding the following to my init seems to the trick.

`exec = require('child_process').exec
exec('source ~/.zshrc')

childProcess = require('child_process')
process.env.PATH = childProcess.execFileSync(process.env.SHELL, ['-i', '-c', 'echo $PATH']).toString().trim()`

**Comment by Arcanemagus** [comment]
@devkinetic Any linter using `atom-linter` to execute it's program should be fixed, if you could file an issue on [atom-linter](https://github.com/AtomLinter/atom-linter) with the linter plugins that aren't working for you that would be helpful.

**Comment by vlasenkov** [comment]
Similar problem here:
AtomLinter/linter-clang#200
