### ISSUE TITLE
Keybinding to show inline tooltips

### ISSUE THREAD

**Issue by albireox** [atom-community/linter#728]
I like the inline tooltips a lot, but they are quite intrusive. Personally I'd rather have the gutter telling me that there is an error/warning and then press a key (while the cursor is on that line) to show the inline tooltip. My suggestion is that alt passes from setting the bubble transparent (I'm not sure what's the use of that) to activating the tooltip while pressed.

**Comment by steelbrain** [comment]
If you have tooltip opened and press alt, it should dim the tooltip.
and Yeah, there should definately be a keybinding to toggle it so you can map it in your keymap

**Comment by albireox** [comment]
Great! And yeah, I understand the idea behind the dim keybinding, and I have tried it, but I fail to see its practical use. But probably there are other people who use it so I don't argue to remove that functionality, only to expand it by allowing the tooltip to appear only while the key is pressed.

**Comment by steelbrain** [comment]
I think you can do it with css in your local `styles.less`. We add a class when we dim the tooltip, you could have a css selector that the `#linter-inline` element and hides it when it doesn't have that dim class and shows it when it does.
