### ISSUE TITLE
Allow Path to be specified as a config

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#743]
Both of these should be implemented:
1. We allow people to specify their `PATH` value in config
2. We allow people to specify path to individual linters in that linter's config (not something we're gonna do in core linter or helper, but still thought I should mention it)

**Comment by steelbrain** [comment]
I need opinions people.
/cc @atom-community/linter-contributors

**Comment by Oletros** [comment]
It seems that it is not exclusive to OS X, I'm receiving the same error using it on Gnome Ubuntu 15.04 with nvm 0.25.4

**Comment by halhenke** [comment]
The overwhelming evidence from #726 seems to be that this was not a problem prior to v1.02/1.01 for anyone and is now effecting a wide range of people.

**Comment by nemoDreamer** [comment]
Correct, @halhenke, and if this was somehow unrelated to linter updates, user error is also not a satisfactory explanation since no users actually changed anything on their end to suddenly break it. The only user-side change might have been a change in the way OS X exposes path, but that seems unlikely, and the issue is cropping up on other OS's as well... The fact that this is suddenly happening for multiple users also points against user error.

**Comment by steelbrain** [comment]
@nemoDreamer this didn't suddenly start happening for multiple users, we've been having reports of this for months. See https://github.com/AtomLinter/Linter/issues/150

**Comment by nemoDreamer** [comment]
I stand corrected, @steelbrain!
But it remains that most reporters mention not having changed anything in their shell setup or path, just opened Atom one day to find linter not working.
Could something have changed in Atom?

**Comment by steelbrain** [comment]
@nemoDreamer I am not entirely sure, by the way, The linter providers are actually the ones who execute the files, You could try downgrading your favorite provider's version one by one to investigate where the error started happening, that would give us a better idea of what's wrong.
In any case, one thing is for sure, that OSX doesn't provide `$PATH` to it's apps started from GUI, and we being package authors can't do anything about it, we can workaround it maybe.
One more 'cause for errors to start increasing could be that when upgrading packages to the new API, provider authors have started to use `jshint` instead of hard-coded `/usr/local/bin/jshint`, while it's a good change, but it'll break it for a lot of people on OSX who had it working already using exact path.

**Comment by nemoDreamer** [comment]
Aha! That would sense... Thanks!

**Comment by Arcanemagus** [comment]
Just a note that might help diagnose the issue: Before whatever it is that broke this happened jshint was working just fine on my Windows computer. Afterwards even setting the path explicitly in the configuration had no effect.

What got this working again was installing node.js on the system. Before this it was using Atom's node instance to run the linter programs. So it seems something broke with utilizing Atom's built in node to run the plugins, and now it requires node to be installed on the system.

**Comment by steelbrain** [comment]
Nooooooo! :sob: that's the actual issue with nodejs, @Arcanemagus You are a genious! I'll fix this bug in `linter-jshint` ASAP.

**Comment by Oletros** [comment]
@Arcanemagus I have node installed via nvm in my Ubuntu and my OS X computers and I have the error.

I could fix it in the OS X modifying my init.coffee script adding
```
process.env.PATH = ["/usr/local/opt/nvm/versions/node/v0.12.5/bin", process.env.PATH].join(":")
```

**Comment by Arcanemagus** [comment]
@Oletros even bypassing the PATH environment variable entirely (by explicitly specifying the `jshint` path) wasn't working on my system, since I didn't have node installed at the system level and it wasn't using Atom's node.

**Comment by joefitzgerald** [comment]
:-1: on this, in favor of fixing this once for all of atom. Watch here: https://github.com/atom-community/environment (currently empty).

**Comment by steelbrain** [comment]
@joefitzgerald the issue above I was talking about is that we were spawning node executables like normal executables, we were using `process.spawn` instead of `process.fork`

**Comment by steelbrain** [comment]
Closing this issue, because we'll be working around this issue in that package referenced above by @joefitzgerald

**Comment by park9140** [comment]
@steelbrain, a bit of history. Forking the atom process used to fail on windows.  I don't know if it has been fixed.  The execution of the node executable was a workaround.

**Comment by steelbrain** [comment]
@park9140 actually, from the when we do `child_process.fork`, it **spawns** a process using the node from the env variable of it's own, see https://github.com/nodejs/io.js/blob/master/lib/child_process.js#L42
PS. Forgot to close

**Comment by park9140** [comment]
@steelbrain, Historically in older versions of atom (This may have been fixed) the `child_process.fork` had issues where you could not communicate or get stdout/stderr on windows.  All I'm saying is that you should really test on windows.

**Comment by steelbrain** [comment]
Gonna test it on windows as soon I am log into one.
