### ISSUE TITLE
Linter panel grows as long as the width of the window

### ISSUE THREAD

**Issue by atilacamurca** [atom-community/linter#746]
When a file has too many errors the linter panel grows as long as the width of the window, leaving no way to edit the file as shown in the picture below:

![linter-too-many-errors](https://cloud.githubusercontent.com/assets/508624/8731819/34a36ea4-2bd0-11e5-80cf-0d0d62eaa0ea.png)

**Comment by AsaAyers** [comment]
The linter panel has a [`max-height`](https://github.com/atom-community/linter/blob/master/styles/linter-plus.less#L50). Do you think you might have a custom style or another plugin that is interfering with this? I just verified using `master` that I don't have this problem and I have a file with 1255 issues.

**Comment by atilacamurca** [comment]
That's my current package list:

$ apm list
Built-in Atom packages (86)
├── archive-view@0.58.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.41.0
├── autocomplete-atom-api@0.9.0
├── autocomplete-css@0.8.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.17.4
├── autocomplete-snippets@1.7.0
├── autoflow@0.25.0
├── autosave@0.21.0
├── background-tips@0.25.0
├── base16-tomorrow-dark-theme@0.26.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.35.0
├── bracket-matcher@0.76.0
├── command-palette@0.36.0
├── deprecation-cop@0.52.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.20.0
├── find-and-replace@0.174.0
├── fuzzy-finder@0.87.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.33.0
├── language-c@0.45.0
├── language-clojure@0.16.0
├── language-coffee-script@0.41.0
├── language-csharp@0.6.0
├── language-css@0.32.0
├── language-gfm@0.77.0
├── language-git@0.10.0
├── language-go@0.27.0
├── language-html@0.40.0
├── language-hyperlink@0.13.0
├── language-java@0.15.0
├── language-javascript@0.80.0
├── language-json@0.15.0
├── language-less@0.27.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.26.0
├── language-php@0.26.0
├── language-property-list@0.8.0
├── language-python@0.36.0
├── language-ruby@0.56.0
├── language-ruby-on-rails@0.22.0
├── language-sass@0.39.0
├── language-shellscript@0.15.0
├── language-source@0.9.0
├── language-sql@0.17.0
├── language-text@0.7.0
├── language-todo@0.25.0
├── language-toml@0.16.0
├── language-xml@0.30.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.150.0
├── notifications@0.56.0
├── one-dark-syntax@0.7.1
├── one-dark-ui@0.9.1
├── one-light-syntax@0.7.0
├── one-light-ui@0.9.1
├── open-on-github@0.37.0
├── package-generator@0.39.0
├── release-notes@0.53.0
├── settings-view@0.208.0
├── snippets@0.95.0
├── solarized-dark-syntax@0.35.0
├── solarized-light-syntax@0.21.0
├── spell-check@0.59.0
├── status-bar@0.74.0
├── styleguide@0.44.0
├── symbols-view@0.99.0
├── tabs@0.81.0
├── timecop@0.31.0
├── tree-view@0.172.0
├── update-package-dependencies@0.10.0
├── welcome@0.29.0
├── whitespace@0.30.0
└── wrap-guide@0.35.0

/home/atila/.atom/packages (12)
├── atom-beautify@0.28.7
├── autoclose-html@0.18.0
├── docblockr@0.7.3
├── js-refactor@0.4.2
├── language-ini@1.11.0
├── linter@1.2.4
├── linter-jshint@1.0.5
├── linter-php@0.0.15
├── monokai@0.14.0
├── pain-split@1.4.0
├── refactor@0.5.1
└── seti-ui@0.7.1

I already check my `~/.atom/styles.less` and that's nothing in it.
This issue is happening in the `linter-jshint`, but I think it just uses `linter` to show the issues.

**Comment by steelbrain** [comment]
@atilacamurca It's actually a theme issue, are you able to repro this with the default themes?

**Comment by atilacamurca** [comment]
After an update, close and open again it's working properly, sorry for the inconvinient.

![linter-fixed](https://cloud.githubusercontent.com/assets/508624/8757047/7ab471b2-2cad-11e5-9f2b-b16d1e8d0ead.png)
