### ISSUE TITLE
it does not run on Atom 1.0

### ISSUE THREAD

**Issue by anGelDcora** [atom-community/linter#747]
I have a problem, it doesn't run in this version of atom, i don't know why.

**Comment by steelbrain** [comment]
Me and a lot of other people are using it on Atom 1.0+
Can you please tell us what's not working for you? and have you installed any linter providers?

**Comment by azer** [comment]
I have the same issue. Installed and not working.

**Comment by Arcanemagus** [comment]
Silly question, but do you have a linter provider installed that will do the actual linting work?

This project provides a framework that consumes linter services from other packages, you can find the whole list here: http://atomlinter.github.io/

**Comment by zaintheinsanebrain** [comment]
I have linter and linter-ruby installed (for the actual linting), but I end up getting 2 deprecated calls that say "AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API". 

How do I go about fixing this?

**Comment by steelbrain** [comment]
@zaintheinsanebrain it's just a warning about the linter providers you have, they are using depreciated API. You could advise them to upgrade to the latest API or maybe PR the change yourself :)

**Comment by zaintheinsanebrain** [comment]
@steelbrain Thank! I'm new all of this and can't really figure it out, and I found [this](https://github.com/atom-community/linter/wiki/Migrating-to-the-new-API). I dont really know what to do with that though... How should I proceed, I cant find those files on Atom either.

**Comment by steelbrain** [comment]
You can safely ignore it, It's just a warning, not an error :)

**Comment by zaintheinsanebrain** [comment]
But Atom still doesn't lint my code. I found the init.coffee file but cant find and edit the package.json.

**Comment by steelbrain** [comment]
@zaintheinsanebrain the work is being done here https://github.com/AtomLinter/linter-ruby/pull/18

**Comment by zaintheinsanebrain** [comment]
@steelbrain Thanks. [This](https://github.com/AtomLinter/linter-ruby/issues/19) is pretty much exactly whats happening on my computer. I'm sorry, but I still don't quite understand what is needed to be done to fix this issue!

**Comment by steelbrain** [comment]
I didn't know I was that confusing :laughing: 
#### The Problem
We've rewrote linter and the previous API the linters are relying upon to provide linting for files is now depreciated and will be moved shortly.
Therefore we're advising package authors to upgrade to the new one.
#### The solution
Upgrade the latest API. and it's something to be done by authors, Users can simply ignore it, and if a package is not working for you, I suggest you contact it's author/owner/maintainer. Instead of reporting at the main repo.

**Comment by zaintheinsanebrain** [comment]
Ah okay, thank you! Sorry, it wasn't that you are confusing its that I'm relatively new to this and don't really know what I'm doing as of yet. Thank you for all the help, your last comment really cleared things up for me!

**Comment by steelbrain** [comment]
Closing as no information was provided by OP
