### ISSUE TITLE
Toggle should disable linter not just for the open buffer but completely

### ISSUE THREAD

**Issue by RobertWHurst** [atom-community/linter#751]
When working on other people's code it can be extremely annoying trying to read the code with a ton of linting errors on the screen. As I see it the point of a linter is to warn you of code style violations in your own code. I don't believe that extends to third party code which I also need to make use of in my editor. I think it would be a vast improvement if toggle disabled and enabled the linter globally. Toggling per buffer is a bit clumsy especially since, if I close the file and reopen it, I have to disable the linter again.

- Atom 1.0.2 on top of OS X version 10.10.4

**Comment by steelbrain** [comment]
If You want to disable linting properly, why not temporarily disable the package?

**Comment by AsaAyers** [comment]
I disagree. My use case is that I'm often viewing code under node_modules
so I need it to only disable for that file.

I can see maybe having a 2nd option, but I don't think single buffer should
be removed or replaced. I think there is an issue somewhere about having a
config per atom project. I'm mobile, so not looking it up here.

**Comment by RobertWHurst** [comment]
@steelbrain Why would I want to open the settings pane every single time I look at another file that wasn't written under my or my team's style guide? And what if there are 20 files in a project, are you going to disable the linter on each of them? Are you going to leave them open, or disable the linter every time you view they're source?

@AsaAyers I get your point, but I think if you want to disable the linter on select files, I'm my opinion that behaviour should be path based. Better to exclude a directory then 20 single files.

Lastly the fact that the disabled state of the linter is forgotten as soon as the buffer is closed is very annoying.

**Comment by pelted** [comment]
I popped in here looking for a way to disable or exclude a linter based on a file path. As mentioned above, the ability to exclude directories such as node_modules, vendor, bower* etc, would be very helpful.

**Comment by steelbrain** [comment]
Closing as it's out of scope of this package to provide a way to disable itself. If you still want it, register a command in `init.coffee` that uses `atom.packages.{enable, disable}Package`. You can then even map it to a key.

**Comment by RobertWHurst** [comment]
Would a PR be considered if I went to the trouble of working on this?

**Comment by steelbrain** [comment]
@RobertWHurst will the solution I posted above not work for someone who wants to achieve this?

**Comment by RobertWHurst** [comment]
It does work, but it's also not very user friendly. Note that this was considered in scope for the authors behind sublime linter.
![screen shot 2015-09-08 at 11 17 16 am](https://cloud.githubusercontent.com/assets/178857/9743461/563950b8-561b-11e5-9e8d-b1ac3341c293.png)

**Comment by steelbrain** [comment]
@RobertWHurst does autocomplete package has an option to disable autocomplete completely?

**Comment by RobertWHurst** [comment]
@steelbrain I don't think it would be a bad idea if they did, however autocomplete doesn't cover 3rd-party code in linting errors; It's not obstructive.

**Comment by steelbrain** [comment]
@RobertWHurst We are working on introducing an option to allow users to ignore certain file types or extensions or names. Until then You can just use that init script.
You can even use the project manager atom package, it enables/disables packages per project.

**Comment by RobertWHurst** [comment]
Yes, I saw the ticket for that. Funny though, I thought @pelted was was +1 my suggestion of path based ignoring, but you've credited him with that idea.

All good, I'll be glad to see it.

**Comment by steelbrain** [comment]
@RobertWHurst sorry I didn't see that you suggested it first :sweat_smile:

**Comment by RobertWHurst** [comment]
@steelbrain No problem at all. Thanks for all the hard work ;)
