### ISSUE TITLE
Add option to disable or defer linting on preview tabs

### ISSUE THREAD

**Issue by forivall** [atom-community/linter#752]
Since atom 1.0.0 introduced preview tabs, (which are helpful while browsing a foreign codebase), it would be nice if there was a setting to disable linting while a tab is in preview mode.

The primary motivation for this is that, while a tab is in preview mode, the user may quickly switch to a different tab, and the linting process often slows down the process of switching to a different tab.

Unfortunately, the preview state is only saved within the TabView itself, so this might not be reasonable unless / until the preview state is made more accessible. Or, instead of preview, the option could be to only lint if it the file has been modified or saved.

**Comment by AsaAyers** [comment]
How do you access these preview tabs? I've never heard of it.

If they're read-only I don't think we should lint them at all

**Comment by joefitzgerald** [comment]
Preview tabs are not read only; they simply close automatically if you don't make any changes. The flow is open file > view content > open a different file (or switch to other tab) > [prior tab closes].

**Comment by steelbrain** [comment]
We could fix this by deferring linting until the first save event.

**Comment by forivall** [comment]
@AsaAyers It's a new setting in the tabs package

![previewtab](https://cloud.githubusercontent.com/assets/760204/8763050/efb82c86-2d40-11e5-83ed-802f6df423ae.png)

**Comment by steelbrain** [comment]
I see that tabs have an `isPreviewTab` attribute[[1]], but how does one get the tab entry by textEditor, any ideas?

[1]:https://github.com/atom/tabs/blob/master/lib/tab-view.coffee#L10

**Comment by steelbrain** [comment]
There is no public API to know if a text editor is a preview one, so I am going to close this for now. I'll be re-opening it when atom announces a public API for that feature

**Comment by forivall** [comment]
Sorry for not updating on this. In any case, it looks like now blocks on atom/atom#9165

**Comment by steelbrain** [comment]
Reopened as #1041
