### ISSUE TITLE
Linter overlaps code at bottom of file

### ISSUE THREAD

**Issue by adambuczynski** [atom-community/linter#758]
When I take a bit too long typing some code at or near the bottom of a file, linter will throw a bunch of errors which overlap the code I'm writing. This is pretty annoying:

![ss](https://www.dropbox.com/s/x7iuufy4liojhur/Screenshot%202015-07-21%2011.44.18.png?dl=1)

Is it possible for the linter to detect if you're at the bottom of the file and make sure that the code you're typing remains visible in the viewport?

**Comment by steelbrain** [comment]
You can choose to disable `lintOnFly` from the settings

**Comment by adambuczynski** [comment]
I know I can disable linting on the fly, and I know I can disable the error box, but that's not a solution.
I like linting on the fly, and I like the error box. It's just behaving very problematic when you're creating linting errors at the bottom of a file.

Could you please re-open the issue and see if someone else has a possible solution?

Thanks!

**Comment by steelbrain** [comment]
Your question is still un-clear, could you please explain it a bit more?

**Comment by adambuczynski** [comment]
Sure thing.

Open a javascript file which has a reasonable amount of code in it, so that you have to scroll to get to the bottom of the file. E.g:

![ss](https://www.dropbox.com/s/aplhj66dn0mohfv/Screenshot%202015-07-21%2011.57.04.png?dl=1)

Then, at the bottom of the file, type some invalid javascript which triggers a bunch of jshint validation errors, for example `func 3`. Note how the linter complete blocks the code you just wrote with the error box:

![ss](https://www.dropbox.com/s/qqren1bvolmc2l9/Screenshot%202015-07-21%2011.57.35.png?dl=1)

Now you have to scroll the view down again to see your code you just typed:

![ss](https://www.dropbox.com/s/h5qkcgo6ufwwk4b/Screenshot%202015-07-21%2011.58.29.png?dl=1)

This is a bit annoying. So I was wondering if maybe the linter can detect if it's going to block the code you're working on from view before the error box is show, and scroll the viewport up to keep the code in view somehow.

**Comment by steelbrain** [comment]
Makes sense Thanks!

**Comment by adambuczynski** [comment]
It might be a wider problem though, as opening the search dialog for example has the same effect!

**Comment by nelson6e65** [comment]
You can check "Scroll Past End" CheckBox in Settings as workaround:
 
![scroll past end](https://cloud.githubusercontent.com/assets/9272498/8793966/9be697b0-2f47-11e5-899e-fb80154a1151.png)

Cheers! :smile:

**Comment by adambuczynski** [comment]
Hmm, good catch. I recall turning that off because it was annoying me, but I'll give it another try in the mean time :+1:

**Comment by AsaAyers** [comment]
> It might be a wider problem though, as opening the search dialog for example has the same effect!

If this is the case, then I think the fix is outside the scope of linter. If you want different behavior you should open an issue in [atom/atom](https://github.com/atom/atom/issues/new). @steelbrain what do you think?

**Comment by iam4x** [comment]
@AsaAyers I agree, this issue is not the first one about it. I recommend users to use `scroll past end` option like @nelson6e65 said.

**Comment by steelbrain** [comment]
@AsaAyers I completely agree with you, maybe core should scroll up/down a little bit when a person writing something is overlapped by a panel!

**Comment by adambuczynski** [comment]
Alright, I'll open an issue in atom/atom for it. Thanks guys

**Comment by adambuczynski** [comment]
Actually, on second thought: there is a difference between the linter dialog showing up and the search dialog for example. The difference being that the search dialog is toggled by the user, so their focus is probably not on the code, and they are using a keyboard command to open the dialog: they expect something to show up.

However, the problem with linter is that it opens the dialog *involuntarily*, while you are still typing, thereby very much distracting you/getting in the way. So not sure if this would be the responsibility of individual packages or atom core? What do you think?

**Comment by AsaAyers** [comment]
I think they still use the same mechanism built into atom. The solution is for that style of panel to not overlap the editor. There's nothing wrong (conceptually) with shrinking the editor to make room and then scrolling so the cursor stays on screen, but that's an issue for core. I don't know anything about the inner workings of making that happen.

**Comment by adambuczynski** [comment]
Yes, good point. I'll raise an issue for it over at atom/atom.

**Comment by steelbrain** [comment]
Closing as it belongs to atom.
