### ISSUE TITLE
set max error window size 

### ISSUE THREAD

**Issue by DavidAwad** [atom-community/linter#760]
I'm getting a full window of errors from a file and can't actually push them out of the way to see the code behind them. 

You also can't resize the window which would be the ideal solution for this problem.

**Comment by DavidAwad** [comment]
![screen shot 2015-07-21 at 1 52 44 pm](https://cloud.githubusercontent.com/assets/4019054/8808509/03e394a8-2fb1-11e5-8133-d31ec09b4d3d.png)

**Comment by steelbrain** [comment]
We're running it fine on Atom's default themes, there's a 99.99999% chance it's a problem in your theme, so just change it and restart atom for it to take effect.
