### ISSUE TITLE
Clarify bottom panel visibility settings

### ISSUE THREAD

**Issue by mnquintana** [atom-community/linter#766]
There used to be an option pre-1.0 to only `Show error of the selected line` in the status bar bottom panel – can this config option be re-added? I find the inline tooltips far too noisy because they obscure the line above or below the selected line, and the current default for bottom panel just shows everything, which in a file with more than a handful (like ~5) linter errors is cumbersome to work with.

**Comment by steelbrain** [comment]
Check your settings view, there should be an option to enable `Line` tab in the bottom panel

**Comment by mnquintana** [comment]
Ah okay :+1:, in that case, it would be great to either rename those Bottom Panel settings, or add help text explaining what they do. It wasn't altogether clear from the current setting names or the UI elements what those tabs actually do.

**Comment by steelbrain** [comment]
They are already quite visible IMO, but I am clearly incorrect as you were unable to recognize it. so I would request you suggest something :)

**Comment by steelbrain** [comment]
@atom-community/linter-contributors should we add a welcome screen or something? that introduces user to these configs.

**Comment by mnquintana** [comment]
> @atom-community/linter-contributors should we add a welcome screen or something? that introduces user to these configs.

I think that would be excessive and too obtrusive. My suggestions would be:

- Add explanatory tooltips for each bottom panel toggle
- Add help text to their corresponding config options in Settings

**Comment by eboracus** [comment]
I agree, adding explanatory text on the config options/renaming them would be very useful. I befell the same problem - whilst searching for that behaviour, it wasn't clear that that's exactly what they did. Also as a very minor alteration, it would be good to change the order that they appear in the settings, currently it's: File, Line, Project.

**Comment by steelbrain** [comment]
We've had a PR recently that added/tweaks descriptions to configs. I think that fixes this
