### ISSUE TITLE
stdout not captured on Windows 8

### ISSUE THREAD

**Issue by timdp** [atom-community/linter#768]
I was originally facing ricardofbarros/linter-js-standard#30, but I've further debugged the issue and it now looks like there is something awry in atom-linter 2.0.1. More specifically, on Windows 8 at least, Atom 1.0.2 seems unable to capture the child process's stdout.

I instrumented `helpers.coffee` to log the various stages of process creation. Basically, I see linter-js-standard invoke `atom.exe` with `ATOM_SHELL_INTERNAL_RUN_AS_NODE=1`. If the file has errors, then the status code differs, so it _is_ linting. However, there is never any standard output and hence no errors.

In a Windows Command Prompt, I did a `set` on the variable above and then ran `atom.exe` with the same arguments. Interestingly, it immediately went to a blank prompt and _then_ showed the output of the linter. It doesn't exhibit this behavior with a regular `node.exe`.

Additionally, I tried overriding `command` with `node.exe` (which is in my `PATH`), and that actually fixed the issue. Hence, it seems as though Electron run as Node behaves differently than a regular Node. It might very well be that the issue is with Electron instead. In that case, atom/electron#1463 should probably be reopened. However, since I've only seen it occur with atom-linter, I wanted to report it here first.

**Comment by steelbrain** [comment]
I have tried linter-jshint on windows 10 beta, and it worked perfectly fine there. Might be a problem with that package :)

**Comment by timdp** [comment]
That's not necessarily relevant. The problem seems to be with `atom.exe` running as Node, which is something that linter-jshint doesn't do. That one just invokes jshint directly.

**Comment by steelbrain** [comment]
@timdp I think you might not have observed the latest version of it, in the latest version of it it runs `atom.exe` with `ATOM_SHELL_INTERNAL_RUN_AS_NODE=1` passing the jshint bin file as an arg. which works.

**Comment by timdp** [comment]
Ah, I wasn't aware of that, but you know best, of course. I was looking at [main.coffee on master](https://github.com/AtomLinter/linter-jshint/blob/master/lib/main.coffee), which currently references the path to jshint pretty clearly.

**Comment by timdp** [comment]
Oh, wait. I see now that it calls `execNode` rather than just spawning it. Sorry about that.

**Comment by timdp** [comment]
Confirmed as a linter-js-standard issue, so I'll close this one. Thanks!
