### ISSUE TITLE
[ERR!] npm run lint 

### ISSUE THREAD

**Issue by jhaoheng** [atom-community/linter#772]
Hi there
When i run 'npm run lint'
and ERR log is 

--
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'lint' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose stack Error: ENOENT, open '/usr/local/bin/package.json'
4 verbose stack     at Error (native)
5 verbose cwd /usr/local/bin
6 error Darwin 14.4.0
7 error argv "node" "/usr/local/bin/npm" "run" "lint"
8 error node v0.12.1
9 error npm  v2.5.1
10 error path /usr/local/bin/package.json
11 error code ENOENT
12 error errno -2
13 error enoent ENOENT, open '/usr/local/bin/package.json'
13 error enoent This is most likely not a problem with npm itself
13 error enoent and is related to npm not being able to find a file.
14 verbose exit [ -2, true ]

--
Then i find i have no 'package.json' file in that folder.

How to fix this error?
Thanks

**Comment by steelbrain** [comment]
Are you getting this when you run `npm run lint` in the linter dir or some other dir?

**Comment by jhaoheng** [comment]
whatever run ```npm run lint``` in linter or other dir are the same ERR.
And i had installed ```npm install lint``` and ```npm install linter``` in /.npm folder.

what operation is missing?
Thanks your feedback.

**Comment by steelbrain** [comment]
I am not sure if linter works like that :sweat_smile: 
It actually provides a base API for Atom's linters, You should install `linter` and then linter providers like `linter-jshint`, `linter-php` and `linter-eslint`.
Then open files of that language in Atom and it will show the results in Atom, it doesn't work in CLI.

**Comment by jhaoheng** [comment]
Ah . i got it.
I just curious ```npm``` type which describe on **Contribute** .

Thanks

**Comment by Arcanemagus** [comment]
Should this be closed? At the very least since this is never intended to be run like that the text mentioned in the **Contribute** section should be removed.

**Comment by steelbrain** [comment]
@Arcanemagus the last time I checked `npm run lint` works.

**Comment by Arcanemagus** [comment]
Ah, you said earlier that you weren't sure it worked like that :wink:.
