### ISSUE TITLE
How do I know which linter am I using? Or if I'm using any?

### ISSUE THREAD

**Issue by wackywendell** [atom-community/linter#773]
I use Atom with a wide variety of file types, and have tried out a few different linters for Javascript, Python, etc. Sometimes, however, I open a file and see "No Issues", but I have no idea whether that means "the linter ran, and found no issues" or "no linter found for this file." 

Similarly, sometimes I get an error I want to look up, and possibly disable; but I no longer remember what Linter is being run on this file. How do I figure out which linter is being run? What if for some strange reason, I have two linters for the same filetype installed; how do I switch between them or figure out which one just ran on the current file?

Perhaps the linter box could have at the right side of the top line something like "linter-jshint" as a link that opens up the settings for that linter plugin; that would make it much easier to figure out linter is being run, and also change settings for the current linter. Or maybe a tooltip for the "1 Issue" thing in the status bar. Or both, to make sure its easy to find, even when no linter is run / no errors are found!

**Comment by Arcanemagus** [comment]
You probably should have split this up into a few issues as you have several different things in this comment. Your second comment is addressed in https://github.com/atom-community/linter/issues/763, in which it is looking like making the linter name be a required attribute is going to go through at least.

As for how it's displayed I would imagine it will be similar to how it was done before, where each linter would have it's own tag, such as the current `Error` and `Warning` tags. But I'm not a UI designer so I'll leave that to others to decide :wink:.

Your first issue sounds like a nice little improvement to me at least.

**Comment by wackywendell** [comment]
Thanks for pointing out #763 to me, I think that pretty much covers things. Maybe I should just add my two cents there, and reference this issue.

As for separating it out: I'm not sure I agree with you. I think you are suggesting separating it like so:

1. Linter should show when a linter is active or not active
2. When active, Linter should show which linter is active
3. How this should be designed (?)

I grouped 1 & 2 because the solution seemed to be pretty much the same: show "Linter Name" somewhere, filling it with something like "No Linter Found" when inactive. As for item 3, I don't really understand why you would suggest splitting suggestions for a solution into a separate issue from the problem, especially when the suggestions are as vague as the two I gave. But I will happily do whatever the repo owners want.

**Comment by Arcanemagus** [comment]
I was interpreting it as you had split your paragraphs, which to me at least would have been two different issues (1, and 2+3) if I was filing it:

1. The first one isn't really covered yet (whether you have a linter available for the open file or not).
1. The second probably will be covered in #763, at least from what I understand.
1. Your third paragraph went on to your suggestion as to how this should be displayed to the user, so I was commenting on how it used to be displayed before the API change a while back.

Sorry for any misinterpretation or confusion on my part. I'm not a repo owner, just trying to help people, so we'll both be waiting to see how things end up :wink: .

Also, I have 3 different linters running for PHP files, so I definitely feel your pain on this issue :confused:.

**Comment by steelbrain** [comment]
In the latest version, linters can specify a `name` attribute and a new config has been added to deal with it.

**Comment by wackywendell** [comment]
@steelbrain That sounds great! Thanks! However, while it sounds like the under-the-hood functionality might be there, I can't see any of it. I just upgraded to 1.7.2 and restarted Atom, and

1. On a file for which I have two linters installed (Python, pylint and flake8) I see no names for which linters are running,
2. On the same set of files for which I have errors, I see no name for which linter gave the error, and
3. On a file (Markdown) for which I have no linters installed, it indicates "No Issues" without telling me that no linter providers are found.

As for the config, I see an option that is simply a checkbox that says `Show Provider Name (when available)`, which I have checked; all other options except `Lint on Fly` are checked. I don't see the `all the time` or `when needed` or `off` option.

Am I missing something? When you say "Latest version", do you mean the latest *released* version?

**Comment by Arcanemagus** [comment]
@wackywendell "linters _can_ specify a name"

I'm not sure how many (if any) `linter-*` providers have updated to support that as of yet since it just landed yesterday :wink:. The ones being actively maintained should update soon, speaking of I should start on that...
