### ISSUE TITLE
Unknown identifier 'x' shown on end curly brace

### ISSUE THREAD

**Issue by jannavarro** [atom-community/linter#774]
I have an end curly brace for an ES6 class that is showing a warning of 'Unknown identifier 'x' ...' Does anyone know what this mean? Even if I remove the curly brace the error is still there.

![image](https://cloud.githubusercontent.com/assets/4499051/8949028/c5b00960-35e0-11e5-9da3-35bb756f37ab.png)

**Comment by steelbrain** [comment]
This bug actually belongs to the linter provider.
