### ISSUE TITLE
Category text in inline tooltips ("error", "warning", ...) illegible in cols near to right window border

### ISSUE THREAD

**Issue by nelson6e65** [atom-community/linter#775]
This happen when error issue is in a line column near to right-window border:

![inline-issue](https://cloud.githubusercontent.com/assets/9272498/8962565/1a400f3a-35e5-11e5-9a39-ccf8a61350d5.png)

**I suggest:**
:one: just draw left-border in corresponding color (in this example, red) and do not include category text; is already show in Error Panel.
:two: add an option to hide category text in linter settings.
:three: automatize direction of tooltip deppending on position.
:four: all above :bowtie:

**Comment by steelbrain** [comment]
Ref: https://github.com/atom-community/linter/pull/745
/cc @simurai

**Comment by iam4x** [comment]
Solution number 3 :+1:

**Comment by steelbrain** [comment]
@iam4x Solution 3 is already done in `inline-messenger`, see https://github.com/atom-community/linter/pull/757

**Comment by simurai** [comment]
Wrapping from #745 should help a bit, otherwise I vote for :three: as well.

**Comment by steelbrain** [comment]
I am glad we agree :clap:

**Comment by steelbrain** [comment]
This has been fixed in the latest release
