### ISSUE TITLE
[suggestion] Simplify text location (line, col) in inline tooltips

### ISSUE THREAD

**Issue by nelson6e65** [atom-community/linter#776]
Example: In tooltips, use `(45:93)` instead of `at in line 45 col 93`, like button-panel in editor already does.

I think this will saves width and it will show much better in small sizes.

**Comment by steelbrain** [comment]
Already done in https://github.com/atom-community/linter/pull/757

**Comment by nelson6e65** [comment]
Nice! :+1: 
When will be released? :grinning:

**Comment by steelbrain** [comment]
Soon is the only time estimate at the momemt
