### ISSUE TITLE
Markdown get linted

### ISSUE THREAD

**Issue by iam4x** [atom-community/linter#777]
https://github.com/AtomLinter/linter-jshint/issues/136
https://github.com/AtomLinter/linter-jscs/issues/62

And I can reproduce it too with `linter-eslint`

Example code:

```markdown

# Some code example with syntax will be linted

```javascript
function () {}
```

The problem is that the whole file is getting linted so it throws a lot errors.

**Comment by steelbrain** [comment]
I have discussed this with @joefitzgerald 
We will be using the scope of the overall file instead of the current cursor to provide correct scopes to linters.

**Comment by iam4x** [comment]
@steelbrain Okey I was going to debug this, so you have a fix in head?

**Comment by steelbrain** [comment]
@iam4x Yeah, use `editor.getGrammar().scopeName` here https://github.com/atom-community/linter/blob/master/lib/linter-registry.coffee#L38

**Comment by reggi** [comment]
This is really really annoying :)

![aug 11 2015 16 01](https://cloud.githubusercontent.com/assets/296798/9209012/56575660-4042-11e5-83b3-ba8d53784ce8.gif)
![screen shot 2015-08-11 at 3 57 32 pm](https://cloud.githubusercontent.com/assets/296798/9209013/56584840-4042-11e5-9c0b-8a66c77a206e.png)

**Comment by steelbrain** [comment]
@iam4x the more I think about it, the more I am convinced that this is a `language-markdown` issue, it should give something like `source.embedded.js` instead of `source.js`, like other languages do.

**Comment by reggi** [comment]
@steelbrain is this fixed?

**Comment by steelbrain** [comment]
@reggi Not really, would you mind opening an issue in `atom/language-markdown`?

**Comment by reggi** [comment]
@steelbrain You mean https://github.com/atom/language-gfm?

**Comment by steelbrain** [comment]
@reggi yeah.
