### ISSUE TITLE
Easy copying for lint warnings / errors

### ISSUE THREAD

**Issue by mehcode** [atom-community/linter#780]
I don't see a way to copy this text? If it is there, what is it? Otherwise, this is a feature request for adding perhaps a copy button.

![screenshot from 2015-07-30 17 14 28](https://cloud.githubusercontent.com/assets/753919/8998135/726054c8-36de-11e5-9dcd-1053d3993e7f.png)

**Comment by steelbrain** [comment]
See https://github.com/mdgriffith/atom-inline-messenger/issues/2
