### ISSUE TITLE
Small UI glitch

### ISSUE THREAD

**Issue by Stanzilla** [atom-community/linter#786]
Steps to repro:

Open a file
Open the settings
Close Atom
Open Atom

In the lower right corner the following UI element shows up, I'm not sure what it is. It only happens when Atom restores the previous session and was focussed on the settings.

![2015-07-25_05-26-02](https://cloud.githubusercontent.com/assets/75278/8887695/b3a3e1de-328d-11e5-999b-ebcae648b7a0.png)

Disabling Linter and/or tabbing away from the settings once and then back fixes it.

**Comment by steelbrain** [comment]
Are you able to repro this issue on the `master` or `next` branch?

**Comment by Stanzilla** [comment]
That was on 1.2.4, so master?

**Comment by steelbrain** [comment]
master has changed a **lot** since the last release, are you saying that you are going to repro this on master or are you already able to repro this on master?

**Comment by Stanzilla** [comment]
Sorry, didn't look when 1.2.4 was released, will try to repro on master later.

**Comment by Stanzilla** [comment]
Eh, how to I switch to master inside of Atom?

**Comment by steelbrain** [comment]
```
cd ~/.atom/packages
rm -rf linter
git clone --depth=1 https://github.com/atom-community/linter
cd linter
apm install
```

**Comment by Stanzilla** [comment]
Can repro on master

**Comment by steelbrain** [comment]
Can you repro the error after doing this
```
mv ~/.atom ~/.atom-bkp
apm install linter
```

**Comment by Stanzilla** [comment]
Can repro with a fresh profile, yes

**Comment by steelbrain** [comment]
Super-weird. I am unable to repro it and would love to hear a minimal repro case.

**Comment by steelbrain** [comment]
I just saw it and it disappeared when I open up dev tools, probably a style issue.
/cc @simurai

**Comment by simurai** [comment]
Hard to say but it looks like the default scrollbar, but just a very small one. I've seen some issues about unstyled scrollbars, here just one: https://github.com/atom/atom/issues/7236

I think it has something to do that the scrollbar gets added after the theme styles are applied and thus just using the default "Chrome" styles.

**Comment by Stanzilla** [comment]
Yeah I also think that it's a scrollbar. And as I said, it only appears when the settings-view was the last thing you looked at and active before you closed and then opened Atom.

**Comment by steelbrain** [comment]
@Stanzilla now that is a solid repro! Mind posting it to the atom bug?

**Comment by Stanzilla** [comment]
Done. I thought I had the repro steps explained pretty well in the original issue text but I guess not :D

**Comment by steelbrain** [comment]
Patched by https://github.com/atom-community/linter/pull/819

**Comment by Stanzilla** [comment]
Confirmed \o/
