### ISSUE TITLE
Error: Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by pcruse3** [atom-community/linter#799]
I am using this with a PHP file and a I get this: `Error: Missing html/text field on Linter Response`

Here is my full log:

```Error: Missing html/text field on Linter Response
  at /Users/pcruse3/.atom/packages/linter/lib/validate.coffee:24:19
  at Array.forEach (native)
  at Object.module.exports.Validate.messages (/Users/pcruse3/.atom/packages/linter/lib/validate.coffee:20:14)
  at MessageRegistry.set (/Users/pcruse3/.atom/packages/linter/lib/message-registry.coffee:22:18)
  at /Users/pcruse3/.atom/packages/linter/lib/linter-plus.coffee:27:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Users/pcruse3/.atom/packages/linter/lib/linter-registry.coffee:57:32
  at process._tickCallback (node.js:367:9)```

**Comment by steelbrain** [comment]
This error should be reopened over to that linter's repo.

**Comment by pcruse3** [comment]
Who's repo? this error is being emitted from your code base, look at the stack trace:
`/packages/linter/lib/`

**Comment by steelbrain** [comment]
I know the error is being emitted from this codebase, but we are actually relying on results from linter provider, and this is a bug in the linter provider :)

**Comment by steelbrain** [comment]
What filetype were you editing when you got this error?

**Comment by jeffaustin81** [comment]
I got this same error message right after I saved my initial app file for a silex application

**Comment by steelbrain** [comment]
@jeffaustin81 what linter provider had you installed for silex apps?

**Comment by jeffaustin81** [comment]
I have the atom linter with a linter-php plugin and a linter-jshint plugin

**Comment by steelbrain** [comment]
Can you provide a code-snippet that repros this error?

**Comment by jeffaustin81** [comment]
I posted the error on twitter https://twitter.com/jeffaustin81

**Comment by jeffaustin81** [comment]
For now I just disabled all my linters and everything is working fine. But would love to continue using linters. It's really helpful for me.

**Comment by steelbrain** [comment]
@jeffaustin81 see https://github.com/AtomLinter/linter-php/issues/57

**Comment by jeffaustin81** [comment]
Thank you so much I really appreciate it!
