### ISSUE TITLE
error: <var> is not a property in Function.prototype

### ISSUE THREAD

**Issue by sksea** [atom-community/linter#802]
I might be overlooking something, but each time I try declaring variables with nested properties, linter generates the following error.
![image](https://cloud.githubusercontent.com/assets/11454733/9069360/ced84f22-3ab6-11e5-8fed-eeae5cff974d.png)

**Comment by Arcanemagus** [comment]
This would be an issue with whatever linter provider is giving the error. The `linter` package is just a framework for running linters.

**Comment by steelbrain** [comment]
Closing based on above comment.

**Comment by Arcanemagus** [comment]
If you know which linter it is please file an issue there so it can be fixed :wink:.
