### ISSUE TITLE
Error Underlining Persists Incorrectly  

### ISSUE THREAD

**Issue by cloudRoutine** [atom-community/linter#808]
( in these cases Linter is being used in conjunction with [atom-fsharp](https://github.com/fsprojects/atom-fsharp) )

![](http://i.imgur.com/1vsZBfs.png)

On the bottom it says there are no issues.

When I close and reopen the file it's fine

![](http://i.imgur.com/xbp4y1o.png)

But then when I start editing the file again it has error underlining that persists

![](http://i.imgur.com/UsGAEQt.png)

**Comment by steelbrain** [comment]
Fixed in the latest release. It was a typo.
