### ISSUE TITLE
Doesn't lint for ruby

### ISSUE THREAD

**Issue by ceres629** [atom-community/linter#809]
linter correctly lints all other languages except ruby where it does nothing. (on OSX yosemite)

**Comment by steelbrain** [comment]
My sense of debugging says that it's because ruby linter hasn't upgraded to the latest API and that API has been removed after the `1.3.0` upgrade, If you want to revert to the older linter do `apm install linter@1.2.4`

**Comment by k2b6s9j** [comment]
Funny you should mention Ruby. Rewriting it with ES6 is on my code to do list next.

**Comment by ceres629** [comment]
@steelbrain 

Your debugging sense was spot on. Reverting to linter 1.2.4 solved the issue!
Many many thanks!

**Comment by k2b6s9j** [comment]
AtomLinter/linter-ruby#21
