### ISSUE TITLE
Enabling the package adds ~5% CPU for every Atom window

### ISSUE THREAD

**Issue by mupkoo** [atom-community/linter#812]
Hello guys,

When I have the package enabled, I get a constant load around 5% for every Atom window.
I have installed two linter packages _(linter-jshint and linter-ruby)_, but disabling them does not effect the load.

I am using Atom on rMBP running OSX 10.9.5

<img width="817" alt="screen shot 2015-08-06 at 17 00 49" src="https://cloud.githubusercontent.com/assets/1788571/9113407/155bb220-3c5d-11e5-9c8a-3cb7eeb69883.png">

This is the activity monitor, running 3 Atom windows.

**Comment by steelbrain** [comment]
Do you get that cpu load on an idle IDE or whenever you add/edit text?

**Comment by mupkoo** [comment]
I get it on idle IDE and I have the **Lint on fly** disabled.

**Comment by steelbrain** [comment]
Does it go away if you disable the core linter?

**Comment by mupkoo** [comment]
Yes. This is how I got to the conclusion that this package is causing the load.

![screen shot 2015-08-06 at 17 12 46](https://cloud.githubusercontent.com/assets/1788571/9113658/6f02279a-3c5e-11e5-89e6-ad8d907c9388.png)
![screen shot 2015-08-06 at 17 12 33](https://cloud.githubusercontent.com/assets/1788571/9113659/6f082c94-3c5e-11e5-9547-b2252bf7f7da.png)

**Comment by steelbrain** [comment]
We are using a `requestAnimationFrame`, maybe it doesn't let the machine be in the rest state. Can you append the line below after this line and report back the statistics https://github.com/atom-community/linter/blob/master/lib/message-registry.coffee#L3
```coffee
requestAnimationFrame = (callback) -> setTimeout(callback, 16.66)
```

**Comment by mupkoo** [comment]
Yep, after line adding the line, the load dropped to ~2.2%

![screen shot 2015-08-06 at 17 22 57](https://cloud.githubusercontent.com/assets/1788571/9113940/ea528362-3c5f-11e5-9139-959e54efb9f5.png)

**Comment by steelbrain** [comment]
What's the status if you change that `16.66` to `60`?

**Comment by mupkoo** [comment]
Dropped to 0.6-0.7

**Comment by steelbrain** [comment]
I think I'll be setting that value to `100` for 10 frames per second in the next release.

**Comment by mupkoo** [comment]
Thank you for the help @steelbrain. I did not expect to solve this so fast :)
