### ISSUE TITLE
Display error in status bar

### ISSUE THREAD

**Issue by gabmontes** [atom-community/linter#814]
The inline tooltip is really good. Anyway, if you are writing code and stop in the middle of a line and the autocomplete tooltip pops up, overlaps the linter one. What about an option to display the current error (in the line where the cursor is) in the status bar as a single line of text?

**Comment by steelbrain** [comment]
We already have that option, search for `Line Tab` in linter configuration :)

**Comment by gabmontes** [comment]
Thanks for the quick response @steelbrain ! 

I saw that options but what about displaying the error inline into the status bar instead of stacking them up on top of it?

**Comment by steelbrain** [comment]
I am not sure if I understand that :sweat_smile:

**Comment by gabmontes** [comment]
What I would like to see is the errors into the status bar as a single line of semicolon sepparated strings:

![linter](https://cloud.githubusercontent.com/assets/2621975/9174049/338852a4-3f54-11e5-849a-5d0ca490291c.jpg)

In the example, we should see "X 2 issues: E030 - Expected an identifier and instead saw ']', at line 45 col 5; E019 - Unmatched...", displaying as much text as fits into the status bar.

**Comment by steelbrain** [comment]
Sorry man, but bottom status bar space comes at a premium 
We have already had our share of criticism after putting those 3 buttons there, showing issues there is just insane IMO :)

**Comment by gabmontes** [comment]
I can hear voices saying "SublimeLinter does exactly that" but, anyway, thanks @steelbrain! AtomLinter is just GREAT!!

**Comment by Arcanemagus** [comment]
SublimeLinter does that because _that's its only available option_, not because they wanted to. It was only recently that Sublime had the capacity for tooltips or anything else like that, yet another instance where Atom has blown far past Sublime.

Also remember that whatever is done here it needs to scale. Putting the message there might work for 1-2 issues, but what about thousands? (I've opened terrible old code with 1.9k issues myself...)

**Comment by gabmontes** [comment]
Thanks for the insights @Arcanemagus. I completely agree with you. And related to the scenario you mentioned, does the linter limit the number of issues that are displayed at once, and avoid filling the whole screen from bottom to top with them? There is no options to to that in the settings page.

**Comment by Arcanemagus** [comment]
It limits them (except for on a few broken themes, but there are other issues on that), it looks like to ~6.5 on my screen (and theme). The rest are accessible via the scrollbar.

**Comment by gabmontes** [comment]
Thanks again!
