### ISSUE TITLE
No linting occuring

### ISSUE THREAD

**Issue by drewprice** [atom-community/linter#815]
I've installed & uninstalled linters (Atom linter with linter-ruby & linter-rubocop), as well as Atom itself, but I still cannot get the linter to catch any errors. 

<img width="1280" alt="screenshot 2015-08-06 23 55 38" src="https://cloud.githubusercontent.com/assets/7977907/9128481/5f25215e-3c97-11e5-82e5-d566bcc1b4a1.png">

Obviously, running a ruby-lint gem catches this as an error, but I get nothing in Atom. The executable path is set to `/Users/drew/.rvm/rubies/ruby-2.2.2/bin/ruby`.

...am I missing something?

Thanks!

**Comment by Arcanemagus** [comment]
It looks like both of those linters are still using the out of date API.

Until https://github.com/AtomLinter/linter-ruby/pull/21 and https://github.com/AtomLinter/linter-rubocop/pull/57 are merged you can downgrade to the older version of linter by running `apm install linter@1.2.4`.

**Comment by drewprice** [comment]
@Arcanemagus—that takes care of it, thanks!
