### ISSUE TITLE
Linter no longer reports deprecated API usage

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#816]
Since 1.3.0 when I removed and re-added, maybe it had a typo?

**Comment by Project0** [comment]
no bug, they removed the deprecated code. Old linter code doesnt work as well.

**Comment by steelbrain** [comment]
@Project0 I removed that code myself :stuck_out_tongue: 
It's not about old linters linting, it's about old linters not being reported as old.

**Comment by Eschon** [comment]
When you open the deprecation cop it still shows the warnings.
It's just the icon in the status bar that is missing for me.

**Comment by steelbrain** [comment]
@Eschon maybe they disabled it's icon in post-1.0?

**Comment by Eschon** [comment]
@steelbrain yeah seems like this was changed recently https://github.com/atom/deprecation-cop/pull/64

**Comment by steelbrain** [comment]
Right.
