### ISSUE TITLE
Strange (seemingly) unrelated error.

### ISSUE THREAD

**Issue by JamenMarz** [atom-community/linter#817]
When the linter is running on a `.js` file with the package [linter-jshint](https://atom.io/packages/linter-jshint).  And you type the following obviously invalid piece of code:

```javascript
if (typeof)
```

You're presented with a dialogue...

![Strange error image](http://i.imgur.com/9DNDkCY.png)

It reads:

> It's a known bug on OSX. See https://github.com/AtomLinter/Linter/issues/726

Linking to a seemingly unrelated issue...

Nothing is wrong with my environment variables as I've seen in the replies of the issue linked.  This error only seems to appear the the previously mentioned JavaScript code is present.

---

 - Atom: 1.0.0
 - OS: Linux Mint Rebecca (17.1)

There are no errors in the console.

**Comment by steelbrain** [comment]
Thanks for the bug report, investigating.

**Comment by JamenMarz** [comment]
I haven't been using linter for very long, but at some point did you have an API update? Because perhaps  the linter-jshint is using some outdated method which is causing that error to display.

Just a toss in the dark.

**Comment by steelbrain** [comment]
You are most probably not on latest `linter` and `linter-jshint`, because I get this error on the latest version of both of them.
```
/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5521 throw err; ^ TypeError: Cannot read property 'identifier' of undefined at Object.nud
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:2396:10) at expression 
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:888:34) at Object.fud 
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:3873:16) at expression 
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:885:32) at statement 
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1635:9) at statements 
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:1678:16) at itself
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/jshint.js:5384:9) at lint
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:487:8) at Object.
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/src/cli.js:619:9) at Socket.
(/home/steel/.atom/packages/linter-jshint/node_modules/jshint/node_modules/cli/cli.js:841:18)

```

**Comment by steelbrain** [comment]
That error points to an internal jshint error, so nothing we can do for it in either `linter`, or `linter-jshint`, You could try posting the result of `jshint test.js` in CLI to `jshint` repo.

**Comment by JamenMarz** [comment]
Alright.

**Comment by JamenMarz** [comment]
Error filed at https://github.com/jshint/jshint/issues/2613, further issues will be reported at either linter-jshint or jshint, as this doesn't seem to be related to linter.

**Comment by JamenMarz** [comment]
I'm actually seeing this popup quite a bit with all sorts of certain patterns. :L
I think I'll remove it locally for the time being.
