### ISSUE TITLE
tab-container throws error on Atom close

### ISSUE THREAD

**Issue by lierdakil** [atom-community/linter#821]
![image](https://cloud.githubusercontent.com/assets/7275622/9177305/29ea9924-3f99-11e5-8036-4521ceb3f322.png)

This actually kills Atom session save/restore for me. Can't get a backtrace, since couldn't reproduce this without closing Atom.

**Comment by steelbrain** [comment]
It is working flawlessly for me, and on both the Travis builds (when we deactivate the package, we don't see a console.log).
Please note that there are some unknown unreproducable cases where some other packages manipulate linter in such a way that it repros that.

From a rough guess, It **might** be possible to repro it with toggleLinter command, also can you repro this with all providers disabled and only jshint?

**Comment by lierdakil** [comment]
This error message goes by extremely fast, and no, I couldn't repro it by simply disabling linter (at least not yet).
I can, however, catch it the following way:
1. Have linter and at least one provider enabled (e.g., I have coffeelint)
2. Start Atom, then close Atom (don't do anything)
3. Check `$ATOM_HOME/nohup.out`, e.g. `$HOME/.atom/nohup.out`. Last line reads `[25616:0810/220137:INFO:CONSOLE(155)] "Uncaught TypeError: Cannot read property 'get' of null", source: /home/livid/github/linter/lib/views/tab-container.coffee (155)` for me.

I couldn't reproduce with *all* providers disabled, but could with either coffeelint, hlint, or both, so I reckon this is a problem with linter itself.

**Comment by lierdakil** [comment]
Oh, no, wait, I think I did it.

**Comment by lierdakil** [comment]
Aw, shucks. Apparently, Atom refused to find an update for base linter package for some ungodly reason, so I was stuck with 1.1.0. After uninstalling and reinstalling new version, everything's fine. You can disregard this. Sorry.

**Comment by steelbrain** [comment]
I am glad you found the problem :clap:
