### ISSUE TITLE
Linting not occuring on the fly

### ISSUE THREAD

**Issue by mneumark** [atom-community/linter#824]
I have been holding off on updating from 1.2.4 for a while due to `linter-ruby` not being upgraded. Then they did update, but it was broken. Finally this morning they got it working again, but it only seems to lint when I save the file.

I checked my settings under `linter` and sure enough `Lint on the fly` is checked.

Any advice?

**Comment by Arcanemagus** [comment]
This should be filed on the [linter-ruby](https://github.com/AtomLinter/linter-ruby) repository, it isn't an issue with the core linter package.

When filing it you might mention to them that as the code currently stands it _says_ it is compatible with lintOnFly, but as they are only feeding the linter the current file name this can only be a lintOnSave linter as it is currently written.

**Comment by mneumark** [comment]
Thanks! Will do.
