### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by signothefish** [atom-community/linter#831]
Every time I save a file, I'm getting the error message: "The filename, directory name, or volume label syntax is incorrect."  Disabling this package resolves the problem.

**Comment by steelbrain** [comment]
Linter does no linting at all, it actually provides an API that it's providers use to lint the files, the bug must be in one of the providers. To find out the buggy provider, check the filetype you were editing then disable providers for that filetype.

**Comment by signothefish** [comment]
I'm using Windows 7, and had backslash characters ("\") in my config.cson file to the linter path, which were being stripped out by Atom.  I replaced them with forward slash ("/") characters to fix the issue.  Thanks so much!  Sorry for the troubles.

**Comment by Arcanemagus** [comment]
Were you manually editing the path into that file, or using the settings inside Atom?

**Comment by signothefish** [comment]
Yes, I had manually edited the path:
 "linter-scss-lint":
    executablePath: "C:/Ruby22-x64/bin/scss-lint"

I had backslashes in the path before, and Atom stripped them out so it looked like:
C:Ruby22-x64binscss-lint

**Comment by steelbrain** [comment]
Yep, Javascript string escaping problems.

**Comment by Arcanemagus** [comment]
Ah, okay I was wondering if somehow a bug had crept into the settings that it wasn't setting things properly :wink:.

**Comment by MayerSonawane** [comment]
Hi @signothefish , I am also facing the same issue which you resolved. 
I am not able to find the file where you manually edited the path. Could you please tell me the location of that particular file where I can find it?

**Comment by Arcanemagus** [comment]
@MayerSonawane _Please_ use the Settings screen in Atom to change settings, the entire bug @signothefish hit was because they had incorrectly edited the file manually.
