### ISSUE TITLE
Specify a way to ignore certain files and dirs

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#838]
Continuing from https://github.com/atom-community/linter/issues/751#issuecomment-128175888 , a suggestion by @pelted. I think it's reasonable to be able to ignore dirs like vendor and bower_components and node_modules and others via the settings.

**Comment by tschaub** [comment]
A setting that would disable the linter for VCS Ignored Files would be very useful ([like `tree-view.hideVcsIgnoredFiles`](https://github.com/atom/tree-view/blob/0f3b554a055995610799ec5131b81b553276684b/lib/directory.coffee#L95-L97)).

This would remove a lot of pain from browsing 3rd party code in a project that uses the linter.

**Comment by steelbrain** [comment]
@tschaub That's a very good idea. and I think it covers the `node_modules` and other cases too!

**Comment by tschaub** [comment]
This works so well.  Thanks @steelbrain.
