### ISSUE TITLE
Linter not working on Windows 10

### ISSUE THREAD

**Issue by grantcarthew** [atom-community/linter#853]
I have deleted my .atom folder and reinstalled all packages.
No linter messages are showing up in the editor.
No linter messages showing up in the debug tools console.

Any ideas?

Current linter packages installed;
linter
linter-jade
linter-eslint
linter-csslint
linter-jsonlint
linter-scss-lint

**Comment by steelbrain** [comment]
My guess is that some of your linter providers are outdated. I have tested some of them myself and they seem to work for me.

**Comment by grantcarthew** [comment]
Hi,
I deleted the .atom folder and reinstalled all packages just now.
Installed eslint globally.
No feedback at all, no errors.
Are there any log files I can check?

I just went through this document;
https://atom.io/docs/v0.186.0/debugging

```
PS C:\Users\Grant> atom --version
[2036:0819/131310:INFO:CONSOLE(0)] 1.0.7

PS C:\Users\Grant> apm links
C:\Users\Grant\.atom\dev\packages (0)
└── (no links)
C:\Users\Grant\.atom\packages (0)
└── (no links)
PS C:\Users\Grant> atom --safe
PS C:\Users\Grant> atom
PS C:\Users\Grant>
```

I can't see any errors anywhere. Or anything saying something about the linter not loading etc.

**Comment by steelbrain** [comment]
@iam4x have you tested `eslint` on windows yet?

**Comment by grantcarthew** [comment]
O.... K....   Now it's working.
Sorry to bother you steelbrain. I don't know what I changed.

Move along, nothing to see here.
