### ISSUE TITLE
Ignored message types

### ISSUE THREAD

**Issue by jacobmischka** [atom-community/linter#856]
This isn't really an issue per se, but a question. I can find zero documentation on what the "Ignored message types" setting is supposed to do, nor have I been able to figure it out by guessing.

I'm basically looking to globally ignore a certain error code. I have seen in closed issues that you opted against implementing this, though this option seems to exist so I'm not sure if there was a changed decision or what is happening really. 

Thank you!

**Comment by Arcanemagus** [comment]
Looking over the code it looks like this is most likely _not_ what you are looking for.

It seems that this lets you ignore all messages with the type string (set by the linter provider) equal to what you set in the setting. So you could set this to "Error" and it wouldn't show any message that the linter provider had set as an error type. This is the entire class of messages though, not a specific message.

**Comment by jacobmischka** [comment]
Okay, thanks!

**Comment by Arcanemagus** [comment]
Most linters support configuration files allowing you to have the linter itself not report the message in the first place, which is usually the best option. If that isn't an option you might try filing an issue on the linter provider that the message is coming from asking them for the ability to filter it?

**Comment by jacobmischka** [comment]
It's a jshint error, and they don't allow you to ignore errors, only warnings. It just keeps complaining about my @laravel lines. Not a huge deal, just a bit annoying.

**Comment by talesa** [comment]
How should I use `linter.ignoredMessageTypes`?  The way I've included it in my config file below doesn't work. 
```
"*":
  "linter":
    ignoredMessageTypes: [
      "Warning",
      "Info"
    ]
```

**Comment by steelbrain** [comment]
Hi @talesa 

This configuration no longer exists in Linter v2, mainly because message types no longer exist in v2, in favor of severities 😛

**Comment by talesa** [comment]
Is there any workaround for that feature now?

**Comment by steelbrain** [comment]
Not that I am aware of, we removed it because all the good linter out there support disabling/enabling based on rules so it was no longer necessary to have it in the base linter.

Further more if you're working in a team, all team members would have to have the same base linter configuration, now you can just configure the underlying linter provider and it'll work consistently for all of you. An example of such linters is `eslint`
