### ISSUE TITLE
Linter doesn't properly lint mixed-language files

### ISSUE THREAD

**Issue by zyklus** [atom-community/linter#858]
I'm seeing this in markdown.  I'm assuming it's because the scope changes to `.source.js` when within a code block.

Example:

```md
# Title

```js
var foo;
```  

# more markdown
```

Whenever I edit text in that JS block, I get an error thrown from the JS Linter that there is an unexpected token on line 1 at `# Title` (which of course isn't valid JS).

**Comment by Arcanemagus** [comment]
It's a known issue with the language specifying the wrong scope: https://github.com/atom/language-gfm/issues/121

**Comment by steelbrain** [comment]
Closing based on comment above
