### ISSUE TITLE
error text not aligned

### ISSUE THREAD

**Issue by jaypanares** [atom-community/linter#859]
Noticing the following alignment issues.  On Windows 10 x64, Atom 1.0.7 and using linter-eslint package.

![capture](https://cloud.githubusercontent.com/assets/7044596/9379737/ec08930a-475d-11e5-840c-7ad0db2ffc60.JPG)

Alignment is still off even if I use default font settings.

**Comment by steelbrain** [comment]
A PR would be appreciated.

**Comment by steelbrain** [comment]
Closing as fixed
