### ISSUE TITLE
Cannot find linter in Atom

### ISSUE THREAD

**Issue by rugk** [atom-community/linter#860]
![linter01](https://cloud.githubusercontent.com/assets/11966684/9387749/53cd95c2-4762-11e5-834f-caee9cade26f.PNG)
![linter02](https://cloud.githubusercontent.com/assets/11966684/9387750/548a8236-4762-11e5-9e5d-477ce445ac28.PNG)

I have no idea why it is not there...

Windows 7
Atom 1.0.7

**Comment by rugk** [comment]
And I can't find it on the web page either: https://atom.io/packages/search?q=linter
[archived version](https://archive.is/SApf7)

**Comment by Arcanemagus** [comment]
It's there, just much further down. Atom's package search is complete garbage, I have no idea what they base it on but I've found most packages need to be specified fully by name, and even then they can be hard to find.

In any case this is an issue with Atom, not the `linter` package.

**Comment by rugk** [comment]
Okay found it. Thanks.
Yes the search is really a kind of stupid.
