### ISSUE TITLE
Sort messages

### ISSUE THREAD

**Issue by Arcanemagus** [atom-community/linter#865]
Edit by @steelbrain
Things to do:
  - [x] Sort by file
  - [ ] Sort by line

The messages in the panel should be sorted by line number (then column, then ?). This will make it so that when multiple linter providers send a message to `linter` things are not completely out of order.

It should also fix an issue where messages from the same provider are out of order, which I think is caused by new messages being added at the bottom while old ones are not touched.

**Comment by steelbrain** [comment]
This is going to be a bit more difficult than I thought, we can sort the messages when they are first added, but because we are using diff based updates (`{added, removed}`). I can't think of a non-dirty way to preserve the order in the messages that are added after the first run.

**Comment by k2b6s9j** [comment]
It should be noted that this is something [`linter-manager`](https://github.com/benjaminRomano/linter-manager) for [`bottom-dock`](https://github.com/benjaminRomano/bottom-dock) by @benjaminRomano does.

**Comment by steelbrain** [comment]
@k2b6s9j but it doesn't do diffed based updating. It's complex with diffed based updating :(

**Comment by steelbrain** [comment]
I have something in mind. I'll be try to open a PR in a few hours.

**Comment by steelbrain** [comment]
Sorting by filePath implemented in https://github.com/atom-community/linter/pull/957

**Comment by brettz9** [comment]
Would be really nice if you could accept an array of messages from your providers to put the messages into separate columns which could in turn be sorted (ideally multiple column sort). My particular interest is seeing eslint allow sorting by warning/error, by error rule type, and/or by line number.

**Comment by steelbrain** [comment]
@brettz9 The solution you ask for comes at a very high price in terms of performance for a lot of errors.

**Comment by brettz9** [comment]
Even if the user does not use the sorting?

**Comment by steelbrain** [comment]
I am not sure if we understand that, it's either all in or all out, if we're going to implement that kinda sorting, we're gonna have some defaults that will sort the messages even if the user hasn't specified their taste yet. so Yeah even if the user doesn't use the sorting. We are using diffing method, we will be patching already present html elements' positions and that is quite complicated and very performance hungry
