### ISSUE TITLE
`Linter:TogglePanel` has no effect?

### ISSUE THREAD

**Issue by posita** [atom-community/linter#874]
Either I'm confused about what `Linter:TogglePanel` is supposed to do, or it has no effect. To reproduce:

* create a file `foo.py` with the contents `import thispackagedoesnotexist`
* install `linter` and `linter-pylint`
* make sure `Show Error Panel at the bottom` is checked in `linter`'s settings
* open `foo.py`
* verify that the following errors are present and displayed in the error panel
  * F:  Unable to import 'foobar' (F0401; import-error)
  * W:  Unused import foobar (W0611; unused-import)
* open the command palette
* select `Linter:TogglePanel`

Nothing happens.

I expected the error panel to disappear (and then reappear if I selected `Linter:TogglePanel` again).

**Comment by steelbrain** [comment]
I'll try to repro, but until then, you can just click the active tab name to toggle it's visibility.

**Comment by steelbrain** [comment]
I just tried to repro and it's working perfectly fine for me, Please confirm that you're on the latest version of linter.

**Comment by posita** [comment]
> I'll try to repro, but until then, you can just click the active tab name to toggle it's visibility.

Clicking the active tab name works for me.

> I just tried to repro and it's working perfectly fine for me, Please confirm that you're on the latest version of linter.

I just checked for updates. I have `linter-1.4.3` and `linter-pylint-1.0.0`.

One thing I didn't mention is that I have 2+ project windows open.

**Comment by posita** [comment]
Hmmm...after restarting Atom, `Linter:TogglePanel` operates as expected in all project windows. My apologies for the false alarm. :blush:
