### ISSUE TITLE
Errors without a positional element are difficult to view

### ISSUE THREAD

**Issue by meatbody** [atom-community/linter#875]
Errors with a specific positional element, such as "line too long" errors, produce an underlined section that exposes the error text when the cursor is placed within it at the location of the error (I have "Underline Issues" checked in my linter settings). However, errors without a positional component, such as a "has no member" error, do not produce this underline and the only way to expose the error is to search through the "Error Panel" at the bottom of the Atom window. For example:

![screen shot 2015-09-02 at 1 28 04 pm](https://cloud.githubusercontent.com/assets/391741/9643585/d0146d94-5177-11e5-92d9-aa579ad9ee23.png)

In the above image, the error is "E1101 Instance of <class> has no 'model' member". I'd expect to see an underlined section on the given line (perhaps where 'model' is referenced), or to have the inline error tooltip show up when I click anywhere on the line.

Atom 1.0.10
linter 1.5.0
linter-pylint 1.0.0
linter-pep8 1.0.1
one-dark-syntax 1.1.0
one-dark-ui 1.0.3

**Comment by steelbrain** [comment]
Would you mind posting your settings for the linter package?

**Comment by steelbrain** [comment]
Closing as a provider bug. Please re-open this in the repo of the provider you're using, as it's the provider who tells us if/where to place a marker.

**Comment by Arcanemagus** [comment]
@meatbody this is probably an issue with `linter-pylint`, can you file an issue over there to get this resolved?

**Comment by meatbody** [comment]
^^^ done.
