### ISSUE TITLE
Linter checks entire file for GitHub-Flavored Markdown code fences

### ISSUE THREAD

**Issue by caleb531** [atom-community/linter#881]
Hi,

I've discovered an interesting issue with Linter and how it handles language-specific code fences in GitHub-Flavored Markdown files. When I create a code fence (with the three backticks) and specify a language on the first line for syntax highlighting, Linter detects this as it should. However, Linter then analyzes the entire file as that language, which produces a excess of errors/warnings.

![Python](https://cloud.githubusercontent.com/assets/872474/9835005/09561c7e-5989-11e5-9570-178418143d56.png)

![JavaScript](https://cloud.githubusercontent.com/assets/872474/9835029/e475b620-5989-11e5-8c04-7e4bdf7d31c9.png)

## How to reproduce

1. Create a new Markdown `.md` file; ensure that the grammar is set as *GitHub Markdown*
2. Add a code fence and specify a Linter-supported language after the first set of backticks
3. Trigger a lint of the file (either by saving or whatever is in accordance with the current user settings)

**Comment by steelbrain** [comment]
That is actually a `language-gfm` issue. See https://github.com/atom/language-gfm/issues/121
