### ISSUE TITLE
linter seems to cause config.cson to be sorted/reversed

### ISSUE THREAD

**Issue by kirjatoukka** [atom-community/linter#883]
At launch, it appears that the `config.cson` is sorted in reverse-alphabetical order, by section. Launching the settings view then causes `config.cson` to be re-sorted in alphabetical order. (However, in some cases I think these have happened the other way around.)

I couldn't reproduce this with no plugins installed, but it does occur with only `linter` installed and enabled, so I'm assuming it's something to do with `linter`.

This is on Mac OS X 10.10.5 with Atom 1.0.11.

Example config:

```
"*":
  "exception-reporting":
    userId: "d73cea11-7484-691d-3884-7da39d96dd04"
  welcome:
    showOnStartup: false
  editor:
    fontFamily: "Source Code Pro"
    fontSize: 12
    invisibles: {}
  core: {}
".python.source":
  editor:
    tabType: "soft"
    tabLength: 4
".ruby.source":
  editor:
    tabType: "soft"
    tabLength: 2
```

Symptom is that the ".python.source" and ".ruby.source" sections will swap around.

**Comment by steelbrain** [comment]
We are not doing anything with your config in our codebase. It could be an atom issue.
Here's how you can fix it
```
mv ~/.atom ~/.atom-backup
apm install linter
atom .
```

**Comment by kirjatoukka** [comment]
Yes, I don't understand how this issue could be caused by linter. However, after backing up my config as you suggest, installing linter, and adding some scoped settings (to make the problem visible), the issue recurs.

A clean configuration does not show this problem, nor does a clean configuration with a randomly-selected other plugin installed. If this is an atom issue, it seems to be one triggered by linter.

**Comment by steelbrain** [comment]
Nowhere in this package are we modifying your config files, we are just using the builtin `atom.config.set` and `atom.config.get` apis for setting and getting configs from a key-value config provided by atom. You should open this up to atom folks.
