### ISSUE TITLE
Linter (and its plugins) is not listed in Atom packages page

### ISSUE THREAD

**Issue by chrisyip** [atom-community/linter#886]
<img width="746" alt="screen shot 2015-09-16 at 4 55 52 pm" src="https://cloud.githubusercontent.com/assets/189559/9900538/0982ef66-5c94-11e5-8359-7b585cba165b.png">

<img width="306" alt="screen shot 2015-09-16 at 4 56 18 pm" src="https://cloud.githubusercontent.com/assets/189559/9900539/09831b4e-5c94-11e5-8bc8-c02c1d26879e.png">

Atom 1.0.11 on Mac OS X 10.11 GM.

**Comment by steelbrain** [comment]
I think this is more of an atom bug than a linter bug :)
Anyways, this might fix it for ya
```
mv ~/.atom ~/.atom-backup
apm install linter
apm install linter-eslint
```
