### ISSUE TITLE
Use PHPStorm style gutter highlights

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#889]
They show error and warning markers in scroll bar, they look pretty neat.
![screenshot](https://cloud.githubusercontent.com/assets/4278113/9951892/7096cdd4-5d8a-11e5-9111-230950cdbbd6.png)

**Comment by Arcanemagus** [comment]
This might conflict with the `minimap` package.

**Comment by steelbrain** [comment]
Well. We already have a minimap package. and a linter binder for minimap. Do we have an option to disable gutter displays? I am a bit busy ATM and can't check

**Comment by Arcanemagus** [comment]
[`minimap-linter`](https://atom.io/packages/minimap-linter) has been working well for me so far :wink:

**Comment by steelbrain** [comment]
True true!
