### ISSUE TITLE
Multiline messages don't appear to work for me.

### ISSUE THREAD

**Issue by nelsonjchen** [atom-community/linter#893]
What am I doing wrong? I've already obliterated my Atom configuration and restarted.

https://www.youtube.com/watch?v=LAgrLTHZT_E

* The disclosure buttons don't appear to work.
* When I use *Expand Multiline Messages* from the command palette and press *Return*, the messages appear briefly and disappear in a flash.
** When I click *Expand Multiline Messages*, it works. 

Here's my config.cson. 

```cson
"*":
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "vim-mode"
      "vim-surround"
      "file-icons"
    ]
  editor:
    invisibles: {}
    fontSize: 11
  "one-dark-ui": {}
  "linter-rust":
    jobsNumber: 8
  linter: {}
```

**Comment by k2b6s9j** [comment]
Can confirm. I just updated `linter-clang` to use multiline messages when applicable and they are not working.

**Comment by steelbrain** [comment]
We are using key up listener to hide messages, You shouldn't invoke `Expand Multiline Messages` from command pellete. You should bind it to a key.

**Comment by steelbrain** [comment]
We could add a click handler on that expand icon to expand it. Sounds like a good feature.

**Comment by nelsonjchen** [comment]
@k2b6s9j Oh gosh I thought I was insane. How about the disclosure buttons?

**Comment by nelsonjchen** [comment]
Ah, ok.

**Comment by nelsonjchen** [comment]
Thanks for clarifying the *Expand Multiline Messages* thing. I thought that was like *Toggle Panel*. I did not realize that was to meant to be pressed and depressed in a bind or a clutch or something.

**Comment by steelbrain** [comment]
It isn't the best ever implementation of multiline messages and we're aware of it. We would love to have your ideas on multiline messages.

**Comment by tomitrescak** [comment]
Multiline messages seem to work quite nicely until latest update when linter is trying to pack them all in the same line ;/ The previous version was doing fine and kept space for longer messages.

![screen shot 2015-09-21 at 18 16 52](https://cloud.githubusercontent.com/assets/2682705/9987685/5989ea08-608d-11e5-89fa-66be0d2da0d4.png)

**Comment by steelbrain** [comment]
@tomitrescak Ouch. That could be because of https://github.com/atom-community/linter/pull/892

**Comment by tomitrescak** [comment]
Is it possible to revert this change? 60% of logs in Typescript are multilines :/ Or maybe some checkbox that would hide the overflow?

**Comment by steelbrain** [comment]
I would love to accept a PR where that PR is reverted and those styles are applied on a selector that makes sure it's not a multi line message, we have separate tagNames or classes for both of them so this should be fairly easy.
