### ISSUE TITLE
Lint on toggle

### ISSUE THREAD

**Issue by shawninder** [atom-community/linter#894]
Currently, if I toggle the linter back on, it only starts linting when I change the content of the file. If I turn the linter back on, I want to immediately tell me where my errors are. This also makes it difficult to differentiate whether my file is clean or I have my linter turned off.

**Comment by steelbrain** [comment]
I would love to accept a PR for this.

**Comment by shawninder** [comment]
Arg, not sure I have time for this. You see I've never done atom package development... But it's Sunday, I'll give it a quick try. No promises

**Comment by steelbrain** [comment]
This can be closed now that the PR has been merged in
