### ISSUE TITLE
Errors near the bottom hide what I'm doing

### ISSUE THREAD

**Issue by shawninder** [atom-community/linter#895]
When writing code, I often create temporary errors (1. declare variable 2. get message for unused variable 3. use variable 4. error disappears)
Since the errors end up disappearing, this is fine. But when this happens near the end of a file, the linter errors that pop up actually hide what I'm working on, forcing me to leave the keyboard, get my mouse and scroll down to finish what I'm writing and fix the errors. This works, but then I have to do the same thing all over again as soon as I create another error (which happens a lot because the linter runs on every new character).

I would like to suggest that when linter errors appear at the bottom, they force a resize on the text viewport or scroll it, anything to make sure my cursor is still visible.

**Comment by steelbrain** [comment]
Have you tried disabling lint on fly?

**Comment by shawninder** [comment]
Not sure I understand what you mean by "on fly". But yes, disabling linting does indeed hide the errors. But then of course I get no linting... So I would qualify that as a workaround; the bug remains.

**Comment by steelbrain** [comment]
Open the settings view, goto `linter` settings, disable lint on fly and try again.

**Comment by shawninder** [comment]
Now it just doesn't lint...

**Comment by steelbrain** [comment]
It lints, but only on save.

**Comment by shawninder** [comment]
Ah I see. That's a good workaround for the time being, thanks

**Comment by steelbrain** [comment]
Closing based on discussion above.

**Comment by shawninder** [comment]
I still think this is a bug... I do want "Lint on fly", I just don't want my cursor to disappear from view. And I can't believe I'm the only one...

**Comment by steelbrain** [comment]
so here's the scenario, `linter` has no idea what is in an error, if you have enabled `lintOnFly` it notifies providers everytime you stop writing. The providers don't know if you are still writing so they give you certain errors. Furthermore, it's perfectly fine to lint only on save. I mean, I only use lint on save and I am quite productive in my development. Each option has it's pros and cons

**Comment by shawninder** [comment]
It's not that it should avoid showing these errors because I want to keep on typing. Rather, it should scroll the text up so that my cursor is still visible even when errors are present. You could see the errors at the bottom as a new element that pushes the text view upwards...

Also, there *is* a "Lint on fly" option, so it should be bug-free. Saying that disabling that option is a good work-flow is not a very good argument :p As you say, each option has it's pros and cons.

Finally, I just noticed atom's `find` function has the same issue (although it's not bothersome in that case). So maybe I'm trying to fix this in the wrong repo...

**Comment by steelbrain** [comment]
> Finally, I just noticed atom's find function has the same issue (although it's not bothersome in that case). 

Yep! We have had bug reports like this and we ended up redirecting them to the atom/atom repo
