### ISSUE TITLE
Linter doesn't find issues

### ISSUE THREAD

**Issue by Sasamus** [atom-community/linter#904]
I've tried to get linter-xmllint working for a while now and was thinking the issue was with it but then I tried a couple of other linters as well (namely linter-gcc and linter-javac) and they didn't work either, so I suspect the issue lies with linter itself.

I'm using the 1.0.19 version of atom and the 1.6.0 version of linter, on an Arch Linux machine.

There's no errors in the developer console, linter simply says "No Issues" no matter if the file have any errors or not.

**Comment by steelbrain** [comment]
Can you try linter-jshint on a js file and tell us if it doesn't work too?
Does this help?
```
mv ~/.atom ~/.atom-backup
apm install linter linter-jshint
```

**Comment by Sasamus** [comment]
linter-jshint works without a fresh .atom folder.

I realized when I was almost asleep that I forgot to mention than I've tried the other three with a new .atom folder and there wasn't any difference.

**Comment by steelbrain** [comment]
Well, if linter-jshint works with a fresh install and others do not. then we can safely say that the problem is not in the core linter but the providers themselves. I would suggest you goto the settings of all of them and add `Executable Path` configs and try again.
