### ISSUE TITLE
Suggestion: Selectable text on warning/error

### ISSUE THREAD

**Issue by tostasqb** [atom-community/linter#909]
I'm a newbie using Atom, been using for....arrghh, 2 days. So forgive me if I'm saying something off here.
For a newbie also using Linter and Rubocop I'm constantly searching for errors and warnings on Google and as simple as it seems I'd like to copy the warning (or parts of) and paste it.

![select](https://cloud.githubusercontent.com/assets/9215716/10166144/9fa77072-66ba-11e5-8c81-0f252647f9ce.png)

**Comment by steelbrain** [comment]
We have had requests for this before, I guess it's atom's internals messing stuff up. The text selection is not disabled by css, I have personally confirmed that. Maybe with javascript?

```html
<!DOCTYPE HTML>
<html>
  <head>
    <script>
      document.onselectstart = function() {
        return false
      }
    </script>
  </head>
  <body>
    <div id="region">You can't select me</div>
  </body>
</html>
```

**Comment by devoncarew** [comment]
Setting `tabIndex="-1"` on the `linter-panel` should do it.

**Comment by steelbrain** [comment]
@devoncarew Thanks that works! The same doesn't work in `#linter-inline` for some reasons :(

**Comment by steelbrain** [comment]
@devoncarew Would you mind doing a PR with that change to `linter-panel`?

**Comment by devoncarew** [comment]
Sure! https://github.com/atom-community/linter/pull/921

**Comment by tostasqb** [comment]
nice one @devoncarew :+1:
