### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeAttribute' of null

### ISSUE THREAD

**Issue by sacred0x01** [atom-community/linter#911]
[Enter steps to reproduce below:]

1. install two of supported json linters 
2. delete https://atom.io/packages/linter-package-json-validator this one
3. receive error

After reinstalling nothing changes 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [linter](https://github.com/atom-community/linter) package, v1.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'removeAttribute' of null

```
At /Users/dsavitsky/.atom/packages/linter/lib/ui/message-element.js:20

TypeError: Cannot read property 'removeAttribute' of null
  at linter-message.updateVisibility (/Users/dsavitsky/.atom/packages/linter/lib/ui/message-element.js:41:130)
  at BottomPanel.setMessages (/Users/dsavitsky/.atom/packages/linter/lib/ui/bottom-panel.js:56:24)
  at LinterViews.render (/Users/dsavitsky/.atom/packages/linter/lib/linter-views.coffee:36:12)
  at /Users/dsavitsky/.atom/packages/linter/lib/linter.coffee:29:14
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at MessageRegistry.updatePublic (/Users/dsavitsky/.atom/packages/linter/lib/message-registry.js:116:20)
  at UpdateMessages (/Users/dsavitsky/.atom/packages/linter/lib/message-registry.js:42:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-csharp",
      "welcome",
      "background-tips",
      "dev-live-reload",
      "jsonlint"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "linter": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.7.0
linter-jsonlint, v1.0.1
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Restart the editor and let me know if this happens again

**Comment by steelbrain** [comment]
A patch release is up for download.

**Comment by franciscotln** [comment]
I'm getting this error in the Chrome's console in any website since I updated it last week to the version 51.0.2704.106 (64bit)
`(program):5 Uncaught TypeError: Cannot read property 'removeAttribute' of null
protectStyleSheet @ chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:393`

**Comment by Arcanemagus** [comment]
@franciscotln Looks like you have a buggy extension, also this repository is _many_ layers removed from having anything to do with Chrome 😛

**Comment by franciscotln** [comment]
Yes, you're right @Arcanemagus . I removed some extensions 2 days ago and I no longer have this issue

**Comment by hubofhugo** [comment]
remove AdBlock
