### ISSUE TITLE
Separate class and badge message parameter

### ISSUE THREAD

**Issue by aipt32** [atom-community/linter#916]
I think it would be neat if you separate the badge class and the badge text.
It would be great if this would be an optional parameter so if you only pass one of them, the class and the text still the same.(like it is now) So all linters still work without an update.
And if you pass one parameter more, one of them is interpreted as the message and one as the class.
e.g. you pass "error" as the class and. e.g the linter name like "jshint" or something else as the text.
In my opinion this is cleaner than passing only the text and define a style for "jshint" class wich mostly is the same like the error or the warning class.

**Comment by steelbrain** [comment]
I am not sure what you mean by that, here's some things that are unclear

 - What do you mean by badge class?
 - What do you mean by badge text?

**Comment by steelbrain** [comment]
If I understand correctly, this has been fixed by #923
