### ISSUE TITLE
new custom gutter breaks styling in some cases

### ISSUE THREAD

**Issue by nylki** [atom-community/linter#918]
![bildschirmfoto von 2015-10-02 01-07-59](https://cloud.githubusercontent.com/assets/1710598/10236113/8d498ffc-68a2-11e5-9add-a2e1c30e5916.png)
This is how the custom gutter by the linter package looks like on my side. (commit: https://github.com/atom-community/linter/pull/901)

I am using the pen-paper-coffee syntax theme (i am the maintainer), which adds a 'margin-right` to the `.gutter` for better readability. Setting other themes, the linter custom element looks ok.

What can we do about it?

**Comment by steelbrain** [comment]
I am not a css guy, so I don't really know what you can do about it, but I am sure @simurai will know

**Comment by simurai** [comment]
Using `.gutter:last-child` for the margin should work.

Or you could move it to the `.gutter-container`: https://github.com/nylki/pen-paper-coffee-syntax/pull/21
