### ISSUE TITLE
Resizing Error Panel overides current auto-adjust behaviour

### ISSUE THREAD

**Issue by eboracus** [atom-community/linter#928]
When using the new resize ability on the bottom error panel, if a size other than the default is chosen, then the panel remains persistent and stays on even when no messages are displayed. So when you move out of its current scope (onto a new line if set to only show messages from the current line, onto a new file if set to display from current file only...) it stays fixed. Unlike the case when left to the default which allows for auto-adjusting its size.

![linter_panel_resize](https://cloud.githubusercontent.com/assets/11758299/10268952/1e2cbf7a-6ac0-11e5-9cfc-5eb7371e7c3c.gif)

I think the optimum behaviour would be to still auto-size in all cases, as is currently done for default, but that the resize should act as the new upper limit (whereas the default is effectively 'unlimited'). So the panel would disappear whenever there are no error messages and still auto adjust if the user, for example, sets the size to ~4 lines and only 1 error is present.

**Comment by steelbrain** [comment]
I think that's actually a feature. People requested resize for that feature, because they didn't like it when panel hid and showed up again. Anyways, you can resize the panel height down to 0 to reset it to it's default behavior.

**Comment by blakeembrey** [comment]
@steelbrain Might be worth adding an extra option for the desired behaviour here though, I can see this annoying myself too :stuck_out_tongue_closed_eyes: Something like "always take up minimum space" so when the space is smaller than the dragged size, we'll resize down and use the dragged size as the "upper maximum". That's how I would expect it to work for me at least, so it's probably worth keeping this around (or creating a new issue) for this feature.

**Comment by eboracus** [comment]
Awesome, nice job! :+1:

Works really nicely now.
