### ISSUE TITLE
Settings aren't showing up

### ISSUE THREAD

**Issue by ismay** [atom-community/linter#932]
I didn't even know that atom-linter had configurable settings until I saw [this](https://camo.githubusercontent.com/0fe233b36477fdb5da45916e731eec61f8f86e7b/687474703a2f2f6f6935392e74696e797069632e636f6d2f3265363574336c2e6a7067). `packages/linter` just shows the readme for me. And no settings whatsoever.

UI Theme: One Dark
Syntax Theme: Base16 Tomorrow Dark
Atom: 1.0.19
Linter: 1.8.1

**Comment by steelbrain** [comment]
```
mv ~/.atom ~/.atom-backup
apm install linter
```
and it should be fixed. It's probably an atom issue.

**Comment by ismay** [comment]
So I have to ditch all my other settings? That's a bit of a brute force fix.

**Comment by steelbrain** [comment]
Try that and see if it works, if it does, open an issue on the atom repo explaining your case. Just so you would know, I have personally talked to severa other people who had the same issue.

**Comment by ismay** [comment]
This worked for me:

```
apm uninstall linter
apm install linter
```

And quitting and restarting atom. Settings are now visible.
