### ISSUE TITLE
Copy selected message text to clipboard

### ISSUE THREAD

**Issue by Arcanemagus** [atom-community/linter#937]
Although https://github.com/atom-community/linter/pull/921 allows the selection of message text, apparently electron doesn't automatically handle copying it to the clipboard when a copy event is fired (Ctrl + C).

Please update linter to handle this case as selectable message text is of little use without being able to copy the error :wink:.

**Comment by steelbrain** [comment]
Thanks for the request!

**Comment by gothy** [comment]
Is it just me or this is broken again in 1.8.0? :(

**Comment by Arcanemagus** [comment]
It was working fine in Atom v.1.8.0-beta4 and is working currently in v1.9.0-beta0, what OS are you on?

**Comment by gothy** [comment]
OS X 10.11.4

**Comment by steelbrain** [comment]
@gothy Please note that the keybindings for OSX *might* be CMD + C *or* CTRL + C, you should try both to see which one works

**Comment by gothy** [comment]
@steelbrain wow! thanks man! `ctrl-c` worked for some reason...

But I've not found anything in `Keybindings` settings for `ctrl-c`. Is this some kind of known issue or there's a way to fix it?

**Comment by steelbrain** [comment]
This has been fixed in the unreleased version
