### ISSUE TITLE
Linter problem

### ISSUE THREAD

**Issue by sumitpatidar** [atom-community/linter#941]
My lint on fly feature not working.

**Comment by steelbrain** [comment]
If it's not working, then it's the provider that doesn't support lint on fly.

**Comment by sumitpatidar** [comment]
suggest some other linters which will work
as currently i am using linter and linter-clang

**Comment by steelbrain** [comment]
Try `linter-jshint` or `linter-eslint` or others like it. `linter-clang` doesn't support lint on fly as to lint every time it has to compile and it's a costly process.

**Comment by jeffschwartz** [comment]
I'm using linter-jshint (v1.2.1) and linter's (v1.8.1) "Lint on fly" option is not working (Atom v1.0.19).

**Comment by steelbrain** [comment]
@jeffschwartz try restarting the editor, if it doesn't help too
```
mv ~/.atom ~/.atom-backup
apm install linter linter-jshint
```

**Comment by jeffschwartz** [comment]
Thanks for the suggestions but having to close and restart Atom surely isn't a solution. Question: What do you suggest to use for Linter's "Lint On Change Interval" option and how does that and the "Lint on fly" option together influence when linter-jshint actually parses the file or script block?

**Comment by jeffschwartz** [comment]
Thanks for the suggestions but still sporadically experiencing this problem. Question: What do you suggest to use for Linter's "Lint On Change Interval" option and how does that and the "Lint on fly" option together influence when linter-jshint actually parses the file or script block?

**Comment by steelbrain** [comment]
We have no such setting like `Lint On Change Interval`, it is a super-super old setting that was removed in the rewrite. There's something wrong with your atom cache.

**Comment by jeffschwartz** [comment]
Ok, thanks so how can I clear the atom cache?

**Comment by steelbrain** [comment]
https://github.com/atom-community/linter/issues/941#issuecomment-146871589 <-- This should've done it. Close atom, do that. Upgrade your atom if an upgrade is available. Start again.

**Comment by jeffschwartz** [comment]
@steelbrain thank you and yup that worked. Having to reinstall all plugins because of one plugin's issues is perhaps not the best solution as I am sure you would agree. I hope in future atom releases support for totally removing all remnants of a plugin and all its meta data throughout all of atom will be supported. Thanks again for your help.
