### ISSUE TITLE
os x yosemite line numbers misaligned when showing gutter indicators

### ISSUE THREAD

**Issue by arnellebalane** [atom-community/linter#944]
![screen shot 2015-10-08 at 10 32 58 pm](https://cloud.githubusercontent.com/assets/1428598/10369560/7ddd3044-6e0d-11e5-820b-f922c3bd80f6.png)

When the linter is disabled the line numbers are perfectly aligned with each other. This is a fresh Atom install, the settings and packages are synced from my Ubuntu machine which didn't have this issue, and I didn't change anything in the styles to override anything in the interface. DevTools doesn't have any errors.

OS: OS X Yosemite 10.10.4
Atom version: 1.0.19
linter version: 1.5.1

**Comment by steelbrain** [comment]
Your linter version is super-old. Update it.

**Comment by arnellebalane** [comment]
@steelbrain thank you so much, that's all that was needed and it worked now. Didn't realize i have lots of outdated packages.
