### ISSUE TITLE
Give back limit for bottom panel

### ISSUE THREAD

**Issue by neumond** [atom-community/linter#949]
Atom 1.0.3
After update I'm forced to disable linter at all :(
Didn't find any config option for this case.

![](http://i.imgur.com/uc5Ta30.png)

**Comment by steelbrain** [comment]
Just restart and it should be fine

**Comment by neumond** [comment]
Oh, nice, it helped.

**Comment by neumond** [comment]
Thank you for such fast support. :heart:
