### ISSUE TITLE
Error from other files show in status bar

### ISSUE THREAD

**Issue by bobrocke** [atom-community/linter#951]
I have 38 issues in my _styles.scss file, but the error count shows even for the unlinted .md file.

![www br dev - atom](https://cloud.githubusercontent.com/assets/2962426/10419454/95c7bdce-7046-11e5-8939-9d72314514a5.jpg)

**Comment by steelbrain** [comment]
You can always configure the scope of the status indicator in `linter.statusIconScope` config

**Comment by bobrocke** [comment]
I'm not sure I understand. The scope of the status indicator is not the active file?

**Comment by steelbrain** [comment]
Yeah. It's set to scope by default.

**Comment by bobrocke** [comment]
So why would the errors displayed not change to the error count of the active window?

**Comment by steelbrain** [comment]
What's your linter version by the way?

**Comment by bobrocke** [comment]
Never mind! I see my error. I had the scope set to project. Let my try it as File.

I have v1.8.1.
