### ISSUE TITLE
No underline and gutter marks not working

### ISSUE THREAD

**Issue by freiksenet** [atom-community/linter#954]
Linter@1.7.2, linter-eslint@3.1.1, tried also with json lint, atom 1.0.19. There is an error in bottom panel and in a popup, but no underlining and no gutter mark.

**Comment by freiksenet** [comment]
Funnily, if I have two panes then one of the panes (right one) will have the gutter mark. I've checked in Dev Tools and it's not a style issue, gutter mark doesn't show up in left pane at all.

**Comment by freiksenet** [comment]
It does seem to be an eslint problem. I guess I'll complain to linter-plugin-eslint.

**Comment by steelbrain** [comment]
Also your linter is outdated. Update it.

**Comment by durz** [comment]
I'm also getting this issue with linter@1.8.1 and linter-eslint@3.1.1. How did you find out it was an eslint problem?

Adding a space or typing any character on the same line as the linting error "refreshes" it and makes the underline + gutter mark appear.

**Comment by steelbrain** [comment]
@durz try this
Close atom
```
apm uninstall linter
apm install linter
```
Start atom

**Comment by durz** [comment]
@steelbrain thanks, but it made no difference.

I disabled atom-beautify because beautification seemed to be removing underlines and gutter marks from the view. I'll continue using Atom without the beautifer for a while and see if this reoccurs.

@freiksenet Are you also using atom-beautify?

**Comment by freiksenet** [comment]
The problem I found was that the mark linter eslint gave was 0 characters long, thus underline didn't work.
