### ISSUE TITLE
Auto-Updates

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#960]
I am thinking of an option, that's enabled by default, that checks for updates for linter package and installs them.

What do you think guys?
cc @k2b6s9j @SpainTrain @Arcanemagus @atom-community/linter-contributors

**Comment by SpainTrain** [comment]
What's the difference from atom's built-in update?  Just no user interaction required, or is there more?

**Comment by steelbrain** [comment]
Users can be pretty lazy, these are auto-updates that'll make sure the user has the latest version of linter always. We're gonna make an npm module for this that other packages can consume too if they want.

**Comment by SpainTrain** [comment]
maybe.  this is another situation where having telemetry on what versions users have installed in the wild would be helpful.

It seems like creating a PR for atom core to support auto update may be a better approach than implementing auto-updates only for a specific package?

**Comment by steelbrain** [comment]
That's an awesome idea!

**Comment by SpainTrain** [comment]
:+1:

**Comment by k2b6s9j** [comment]
Or... Someone could create a auto-update package...

**Comment by k2b6s9j** [comment]
Say it's highly recommended with a linter install, but not required...

**Comment by steelbrain** [comment]
@k2b6s9j my initial idea was to have a config, we could have it disabled by default, it would be better than a completely separate packaage

**Comment by Arcanemagus** [comment]
@steelbrain the type of user that doesn't install updates in the first place isn't going to bother going into the settings to enable something like this either :wink:.

**Comment by steelbrain** [comment]
Agreed on that one

**Comment by johanneswuerbach** [comment]
Using https://atom.io/packages/auto-update-packages for a long time now and am pretty happy with it.

**Comment by steelbrain** [comment]
@johanneswuerbach Thank you for your suggestion but that package is pretty unmaintained and we want this functionality in linter only that's enabled by default, we don't want to update other packages for the user as the user might want to keep that version. Also if we manage this in our package we can have an option for it.

**Comment by steelbrain** [comment]
I'm going to start working on an npm package for this now, here's how it's API would look like
```js
export default {
  upgrade(name = null): void
}
```
