### ISSUE TITLE
A better self-API

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#964]
Here's what I have in mind
```coffee
consumeLinter: (linterRegistryHelper) ->
  linterAgent = linterRegistryHelper.registerLinter({
    name: 'some-linter'
  })
  linterAgent.setMessages([...messages...])
  linterAgent.deleteMessages()

  @subscriptions.add(linterAgent) # or
  linterAgent.dispose() # automatically deletes everything of this agent
```
^ It should make a lot of things simpler. We have been told that our self-API isn't as beautiful so now that we're done with high priority things, I think this is the best time to work on it

cc @radicaled @devoncarew @david-driscoll @russpowers

^ authors of packages using self-API. I did a quick github code search if I've missed somebody, please ping them on here

CHANGELOG
 - Removed `scope` from the API. I haven't seen a PUSH style linter that is per file yet, If you have, let me know.

**Comment by kepler0** [comment]
And I just started using this for atom-build...

This does look better though.

**Comment by kepler0** [comment]
What about methods to find all messages for packages like `minimap-linter`?

**Comment by steelbrain** [comment]
@kepler0 those methods are gonna stay as-is. Those methods are pretty fine, it's just that I was told recently that linter doesn't support PUSH mechanism and only supports PULL mechanism to which I replied with self-API and they said it wasn't documented anywhere and they were right.

Packages using self-API for non-provider purposes have too broad coverage, we can not wrap all of that, but we can polish our provider self-api because that's what this package is for.

**Comment by kepler0** [comment]
Awesome. Just making sure that these won't be the only methods exposed.

**Comment by devoncarew** [comment]
So, my drive-by comment -

We've been able to build what we need to on the current self API. This iteration looks good; happy to consume that as well :) We would appreciate a period of overlap - where we could move to the new API, but the current would would continue to be available.

**Comment by steelbrain** [comment]
@devoncarew Absolutely, even when we roll that API out, the current packages will continue working 100%

**Comment by steelbrain** [comment]
I'll start working on this now.

**Comment by kepler0** [comment]
HYPE!

**Comment by steelbrain** [comment]
Added in #986
