### ISSUE TITLE
Allow excluding certain non-VCS ignored files from lint

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#968]
Ref: https://github.com/wooorm/atom-linter-alex/issues/8#issuecomment-150713922

**Comment by steelbrain** [comment]
I think I am gonna allow glob excluding for this

**Comment by blakeembrey** [comment]
Is this a setting on per-linter configuration?

**Comment by steelbrain** [comment]
@blakeembrey I don't think so. Linter providers **can** implement this as an option and comply to it by returning an empty errors array for those files. But for now I am just doing it in the core. It'll help people to things like `*.min.{js,css}` files in the repo

**Comment by steelbrain** [comment]
@blakeembrey For the record, I've demo-ed the per provider version of this in a linter-alex issue https://github.com/wooorm/atom-linter-alex/issues/8#issuecomment-150772117
