### ISSUE TITLE
Error : special characters must be escaped : [<] or [>]

### ISSUE THREAD

**Issue by eved42** [atom-community/linter#973]
Hi everyone,
since the last update, all my php files have this error every time I use theses characters "<" and ">".

Error on line 1 : 
```
<?php
```
or still on : 
```
echo "<p>Hello !</p>";
```

It is really annoying because I have a very high number of errors in my files and the linter is more binding than helpful... (example : a file with 340 lines have 141 issues...).

Before the last update, everything worked well.

Can you correct this please ? Thanks.

**Comment by steelbrain** [comment]
It's actually a provider issue, we have two fields `text` and `html`, if the provider uses `text` we escape it for the provider, if they use `html` providers will have to escape themselves

**Comment by steelbrain** [comment]
@Arcanemagus (presuming this issue is in linter-*) ^

**Comment by eved42** [comment]
So, what do I have to do? Wait that linter-php is updated ?

**Comment by steelbrain** [comment]
@eved42 Yep, you should ask the maintainer of the provider repo to fix this.

**Comment by Arcanemagus** [comment]
This isn't linter-php, I'm pretty sure it's linter-htmlhint, I'll provide more info in the other issue.
