### ISSUE TITLE
Adding external links to open in browser

### ISSUE THREAD

**Issue by brettz9** [atom-community/linter#974]
Hi... Just wondering whether providers can create external links that open in the browser? If so, just create a normal `<a href=>` link or something else needed like a "target" attribute or something? 

(I asked this on chat, but didn't receive a reply, so sorry if this is "support")

**Comment by steelbrain** [comment]
You could provide an HTML element with a listener, but when we show it, we clone and show it so that wouldn't work.

**Comment by brettz9** [comment]
It would be great to have this for the sake of e.g., linking to linter rules with a full description of the rule and its rationale...

**Comment by steelbrain** [comment]
This has been fixed as we've added a method in the helper module that allows you to create elements whose events survive clones.
Here's how you would create a message like that

```
Helper = require('atom-linter')
Shell = require('shell') # Electron's internal module
lint: (textEditor) ->
  path = textEditor.getPath()
  element = Helper.createElement('span')
  element.innerHTML = 'Something went wrong, <a href="javascript:void">Click here to know more</a>'
  element.addEventListener('click', (e) ->
    return unless e.target.tagName is 'A'
    Shell.openExternal("https://google.com")
  )
  return [{
    filePath: path,
    type: 'Error',
    html: element
  }]
```
