### ISSUE TITLE
Have both html and text in messages

### ISSUE THREAD

**Issue by benjaminRomano** [atom-community/linter#976]
Currently for my package, [linter-manager](https://github.com/benjaminRomano/linter-manager), I have my own custom views for messages. 

However, some linters create messages using html that only works for this package's views. 

Would it be possible to add an extra property to messages such as htmlText that could be used as an alternative to message html? Otherwise, is it possible to make having both html and text properties on a message valid?

**Comment by steelbrain** [comment]
I think a better solution would be for `linter-manager` to support both `text` and `html` attributes, it's super simple to support both. If you have any reasons not to, please do state them.
Here's how we do it https://github.com/atom-community/linter/blob/master/lib/ui/message-element.js#L65-L81

**Comment by benjaminRomano** [comment]
My issue with just supporting html is that people create these custom elements with only your views in mind. For the majority of custom elements, this is fine, but it isn't a guarantee. 
I'd prefer having the choice of just displaying text since it's more reliable.

**Comment by steelbrain** [comment]
@benjaminRomano this way I mentioned above isn't really exclusive to custom elements, they work the same with normal `divs` like
```
someDiv = document.createElement('div') // or document.getElementById('someDiv')
if (message.html) {
  someDiv.appendChild(typeof message.html === 'string' ? document.createTextNode(message.html) : message.html)
} else if (message.text) {
  someDiv.textContent = message.text
}
```
This is simple DOM manipulation with JS, really, nothing related to custom elements here

**Comment by benjaminRomano** [comment]
I guess I misspoke, I meant custom styling more so than custom elements. 

It seems like the chance of having the html break my view is very low, so I'll just support it.
