### ISSUE TITLE
Extra Semicolon 

### ISSUE THREAD

**Issue by EndlessPineapples** [atom-community/linter#977]
all declaration statements give a warning for extra semicolon when there are none.

**Comment by kepler0** [comment]
Which linters do you have installed?

**Comment by steelbrain** [comment]
I think it's either `linter-jshint` or `linter-eslint`. More changes are it's `linter-jshint`. I would advise you to tweak your linters' config using either `.jshintrc` or `.eslintr ` and disabling the semi-colon rule from there.
