### ISSUE TITLE
Show icon when linting is in progress

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#992]
I really like the analyzing text here: https://github.com/dart-atom/dartlang/issues/61#issuecomment-131282542

**Comment by kepler0** [comment]
I was thinking about this today and believe that we should outsource this to a process running indicator service package. Something which would benefit both Linter and Build.

I think I may work on it this weekend.

**Comment by steelbrain** [comment]
@kepler0 I don't mind that, but what if the user doesn't have that package installed? Will the user have to install a whole build package just to see the indicator? I think I have a better idea, we already have a linter status icon which shows `No Errors` or `X Errors`, if we change it's icon to the loading icon while linting is in progress, it should do the job. What do you think?

**Comment by kepler0** [comment]
What I was trying to say is that it would be a new service, we would consume. So say the service name is `status-indicator`, the user would then be able to use a `indicator-bottom` package which would provide a graphical interface for the statuses of packages consuming the service. So in this instance the `linter`, `build`, and `dartlang` packages would be consuming the service and `indicator-bottom` would display activity in the bottom bar.

**Comment by kepler0** [comment]
I'll have a better use-case this weekend.

**Comment by kepler0** [comment]
And probably a demo too.

**Comment by kepler0** [comment]
I think that changing the Error indicator like that could work well, if a broader solution isn't made available.

**Comment by KnutHelland** [comment]
Such indicator should at least only be displayed when linting is manually triggered, and not when it is automatically linting when typing. Anything else would just be disturbing.

And there are probably not many users calling lint manually. This is probably something that is most interesting for you who have a developer-relationship to this package. We users just want it to work and not disturb us on anything else than errors with our code :)

And if this is going to be used by very few people anyway, I agree with @kepler0 that it would be better to  consume some other package for this functionality.

**Comment by steelbrain** [comment]
@KnutHelland I might have not been much clearer in my messages above, let me fix that now :)

The indicator is going to be a tiny size, the same size that the x or tick icons are now in the bottom panel. I personally don't think it's gonna bother anybody or act as a distraction, even if it is, it'll be the same amount of distraction as is the `x` icon with changing count right now, most people including myself don't even notice it.

Even then if it bothers somebody, I guess you might have noticed that everything in linter is configurable, so this behavior will be configurable too! You can just opt out of it if you don't like it. Also even if it's used by very few people, we still won't be able to conditionally install the dependency and it would be an overkill, we already have an indicator, users will expect us to show linting status on that and only that indicator, users won't expect to have a linting indicator next to the git lines diff. It would create a lot of confusion and we, by all means, are trying to reduce that :)

**Comment by KnutHelland** [comment]
Hehe, okay :+1: I just saw the indicator you linked to and thought that was very verbose. Something you would like to have when you manually start a background process, like for example a build process. But I think linting is another category of service. That's one of many background services in an editor that the end user in a perfect world shouldn't think of as a background service, but as a instant feature of the editor. It should ideally lint instantly without any latency and any need for an indicator.

There are probably dozens of other processes happening in the background of atom as well, without indicating anything to the user. Things like autosaving, garbage collecting, sending usage statistics to NSA, etc. I'm not saying that linting is comparable to these. But I think that displaying a loading indicator to a user is something that one generally shouldn't do unless it is valuable for the user to know that he is waiting on a result from an ongoing process. And 99.99% of the times linter runs, I'm not waiting for anything. I'm just coding.

But yeah, anyway. I don't really care. Don't know why I suddenly happened to write a comment here. And it is really nice that things are very configurable. Thumbs up! I would however vote for this one to be disabled by default, even if it is barely noticeable. I still think this is unnecessary information overload to the UI, and something the user shouldn't need to know. It goes against my personal "keep it simple" UI agenda :)

**Comment by steelbrain** [comment]
@KnutHelland Just to clear the confusion that I have not implemented an icon this far because I believed linting is instant and user wouldn't even notice it. But I've seen cases where a linting is in progress, user tries to lint again, his request is ignored in favor of already in progress linting and user thinks the linter is not responding. Currently there is **no way** for the user to know if something's happening, I just want to fill that gap :)

**Comment by steelbrain** [comment]
Moved to https://github.com/AtomLinter/linter-ui-default/issues/53
