### ISSUE TITLE
Linting the wrong file type

### ISSUE THREAD

**Issue by seriema** [atom-community/linter#996]
I'm creating the issue here, since it's the same issue for both [linter-xo](https://atom.io/packages/linter-xo) and [linter-jshint](https://atom.io/packages/linter-jshint) I'm assuming it's upstream.

It's trying to lint the wrong filetype. In this, two js-linters are trying to make sense of my markdown file.
<img width="1238" alt="screenshot 2015-11-08 07 57 25" src="https://cloud.githubusercontent.com/assets/693684/11019280/0ab2f5c0-85f2-11e5-8d67-b32a267373cb.png">

I have Atom `1.1.0` (OSX) and the latest packages.

**Comment by steelbrain** [comment]
It's a bug in `language-gfm`. https://github.com/atom/language-gfm/issues/121
