### ISSUE TITLE
Url in error popup and error panel not linkable / nor can i copy-n-paste

### ISSUE THREAD

**Issue by jonyeezs** [atom-community/linter#997]
Hi,
I saw that you had an old ticket when linter-plus was in development: https://github.com/atom-community/linter/issues/547

I'm not sure if this has been implemented.

Scenario: I'm using linter-rubocop. It has links to the rules description. But i can't seem to click on the url links.

If that would not be feasible, atleast i should be able to copy the text in the error panel?
I seem to be able to highlight the text but i can't copy it.

**Comment by steelbrain** [comment]
You can copy text from the bottom panel but you can't open them as of yet. See #974
Feel free to discuss if this issue is different
