### ISSUE TITLE
Linter Toggle fails to remove bubble gutter on left

### ISSUE THREAD

**Issue by sci-phi** [atom-community/linter#998]
When first opening a file from the tree view, the linter is invoked (say, rubocop on a foo.rb file) and a gutter is added to the left hand side of the content window. If you then use linter toggle to try to dismiss it, the panel is hidden but the gutter with the line 'bubbles' remains. You can toggle linter on and then off again and the gutter will get removed, it just never works the first time, in my experience.

![linter-toggle-bug-01](https://cloud.githubusercontent.com/assets/29684/11052916/ab19df72-872a-11e5-8ea2-52fd9b173676.png)
![linter-toggle-bug-02](https://cloud.githubusercontent.com/assets/29684/11052917/ab256e82-872a-11e5-80fd-05dc673de105.png)
![linter-toggle-bug-03](https://cloud.githubusercontent.com/assets/29684/11052918/ab2b1094-872a-11e5-820d-2462f397ae8f.png)

**Comment by steelbrain** [comment]
I am unable to repro this on the latest version of linter and Atom
Can you please provide some way to repro this?

**Comment by sci-phi** [comment]
Mac OS X 10.10.5, Atom 1.1.10, Linter 1.10.0, Linter-RuboCop 0.4.4, Ruby 2.1.4, Rucocop 0.34.2  (parser/ruby21, 2.1.7-compliant syntax)

Steps:
Close all open files
Open a Ruby file
Toggle Linter
Gutter Remains < BUG
Toggle Linter
Toggle Linter
Gutter Removed < Expected Behavior

**Comment by steelbrain** [comment]
I was able to repro this and have fixed in the UI improvements branch

**Comment by sci-phi** [comment]
😎
